import { Label } from ".";

export function resolveDutch(text: Label): string {
    switch (text) {
        case Label.Ok: return "OK";
        case Label.Cancel: return "Annuleren";
        case Label.Settings: return "Instellingen";
        case Label.Language: return "Taal";
        case Label.LanguageDescription: return "Stelt de taal in die in de applicatie wordt gebruikt.";
        case Label.LanguageAuto: return "Automatisch";
        case Label.HotkeysHeading: return "Sneltoetsen";
        case Label.GeneralHeading: return "Algemeen";
        case Label.NetworkHeading: return "Netwerk";
        case Label.FrameRate: return "Framesnelheid";
        case Label.FrameRateDescription: return "Bepaalt de framesnelheid waarmee de timer wordt weergegeven. “Batterijbewust” probeert op basis van apparaattype en laadstatus een goede framesnelheid te kiezen. “Scherm overeenkomen” laat de timer overeenkomen met de verversingssnelheid van het scherm.";
        case Label.FrameRateBatteryAware: return "Batterijbewust";
        case Label.FrameRateMatchScreen: return "Scherm overeenkomen";
        case Label.SaveOnReset: return "Opslaan bij reset";
        case Label.SaveOnResetDescription: return "Bepaalt of de splits automatisch worden opgeslagen bij het resetten van de timer.";
        case Label.ShowControlButtons: return "Bedieningsknoppen tonen";
        case Label.ShowControlButtonsDescription: return "Bepaalt of er knoppen onder de timer worden getoond om deze te bedienen. Als dit is uitgeschakeld, moet je de sneltoetsen gebruiken.";
        case Label.ShowManualGameTimeInput: return "Handmatige speltijdinvoer tonen";
        case Label.ShowManualGameTimeInputDescription: return "Toont een tekstvak onder de timer waarmee je de speltijd handmatig kunt invoeren. Je start de timer en splitst door op Enter in het tekstvak te drukken. Zorg dat je vergelijkt met “Game Time”.";
        case Label.ManualGameTimeMode: return "Handmatige speltijdmodus";
        case Label.ManualGameTimeModeDescription: return "Bepaalt of de handmatige speltijd wordt ingevoerd als segmenttijden of split tijden.";
        case Label.ManualGameTimeModeSegmentTimes: return "Segmenttijden";
        case Label.ManualGameTimeModeSplitTimes: return "Split tijden";
        case Label.AlwaysOnTop: return "Altijd bovenaan";
        case Label.AlwaysOnTopDescription: return "Houdt het venster altijd boven andere vensters.";
        case Label.SpeedrunComIntegration: return "Speedrun.com-integratie";
        case Label.SpeedrunComIntegrationDescription: return "Vraagt de lijst met games, categorieën en ranglijsten op van speedrun.com.";
        case Label.ServerConnection: return "Serververbinding";
        case Label.ServerConnectionDescription: return "Staat toe om verbinding te maken met een WebSocket-server die de timer kan besturen door verschillende opdrachten te verzenden. De opdrachten zijn momenteel een subset van de opdrachten die de originele LiveSplit ondersteunt.";
        case Label.ServerConnectionExperimental: return "Deze functie is experimenteel en het protocol zal waarschijnlijk in de toekomst veranderen.";
        case Label.HotkeyAlreadyInUse: return "De sneltoets is al in gebruik.";
        case Label.Start: return "Start";
        case Label.Resume: return "Hervatten";
        case Label.Pause: return "Pauze";
        case Label.UndoSplit: return "Split ongedaan maken";
        case Label.Reset: return "Reset";
        case Label.SkipSplit: return "Split overslaan";
        case Label.ManualGameTimePlaceholder: return "Handmatige speltijd";
        case Label.LiveSplitLogoAlt: return "LiveSplit‑logo";
        case Label.LiveSplitOne: return "LiveSplit One";
        case Label.Splits: return "Splits";
        case Label.Layout: return "Lay‑out";
        case Label.CompareAgainst: return "Vergelijken met";
        case Label.RealTime: return "Realtime";
        case Label.GameTime: return "Speltijd";
        case Label.PopOut: return "Pop‑out";
        case Label.About: return "Over";
        case Label.Back: return "Terug";
        case Label.AboutVersionPrefix: return "Versie:";
        case Label.AboutDescription: return "LiveSplit One is een multiplatform‑versie van LiveSplit, de strakke en zeer aanpasbare timer voor speedrunners.";
        case Label.AboutViewSource: return "Bekijk de broncode op GitHub";
        case Label.AboutRecentChanges: return "Recente wijzigingen";
        case Label.AboutContributors: return "Bijdragers";
        case Label.Loading: return "Laden...";
        case Label.Add: return "Toevoegen";
        case Label.Import: return "Importeren";
        case Label.OpenSplits: return "Splits openen";
        case Label.EditSplits: return "Splits bewerken";
        case Label.ExportSplits: return "Splits exporteren";
        case Label.CopySplits: return "Splits kopiëren";
        case Label.RemoveSplits: return "Splits verwijderen";
        case Label.Untitled: return "Naamloos";
        case Label.NoCategory: return "—";
        case Label.DiscardChangesTitle: return "Wijzigingen verwerpen?";
        case Label.DiscardChangesDescription: return "Je huidige splits zijn gewijzigd en hebben niet-opgeslagen wijzigingen. Wil je doorgaan en die wijzigingen verwerpen?";
        case Label.DeleteSplitsTitle: return "Splits verwijderen?";
        case Label.DeleteSplitsDescription: return "Weet je zeker dat je de splits wilt verwijderen? Deze bewerking kan niet ongedaan worden gemaakt.";
        case Label.SaveBestTimesTitle: return "Beste tijden opslaan?";
        case Label.SaveBestTimesDescription: return "Je hebt enkele van je beste tijden verbeterd. Wil je ze bijwerken?";
        case Label.Yes: return "Ja";
        case Label.No: return "Nee";
        case Label.DontReset: return "Niet resetten";
        case Label.FailedToExportSplits: return "Exporteren van de splits is mislukt.";
        case Label.CantImportEmptySplits: return "Kan geen lege splits importeren.";
        case Label.FailedToReadFile: return "Bestand lezen mislukt:";
        case Label.FailedToImportSplits: return "Splits importeren mislukt:";
        case Label.CouldNotParseSplits: return "Kon de splits niet parseren.";
        case Label.LoadedSplitsInvalid: return "De geladen splits zijn ongeldig.";
        case Label.NewSegmentName: return "Tijd";
        case Label.EditWhileRunningError: return "Je kunt je splits niet bewerken terwijl de timer loopt.";
        case Label.Edit: return "Bewerken";
        case Label.Save: return "Opslaan";
        case Label.Export: return "Exporteren";
        case Label.FailedToParseTimeSpan: return "TimeSpan kon niet worden geparseerd";
        case Label.Default: return "Standaard";
        case Label.Game: return "Game";
        case Label.Category: return "Categorie";
        case Label.StartTimerAt: return "Timer starten op";
        case Label.Attempts: return "Pogingen";
        case Label.SplitsEditor: return "Splits‑editor";
        case Label.Variables: return "Variabelen";
        case Label.Rules: return "Regels";
        case Label.Leaderboard: return "Leaderboard";
        case Label.InsertAbove: return "Boven invoegen";
        case Label.InsertBelow: return "Onder invoegen";
        case Label.RemoveSegment: return "Segment verwijderen";
        case Label.MoveUp: return "Omhoog";
        case Label.MoveDown: return "Omlaag";
        case Label.AddVariable: return "Variabele toevoegen";
        case Label.OpenPbPage: return "PB‑pagina openen";
        case Label.AssociateRun: return "Run koppelen";
        case Label.Icon: return "Pictogram";
        case Label.SegmentName: return "Segmentnaam";
        case Label.SplitTime: return "Split‑tijd";
        case Label.SegmentTime: return "Segmenttijd";
        case Label.BestSegment: return "Beste segment";
        case Label.SpeedrunComVariableTooltip: return "Een speedrun.com‑variabele specifiek voor de game.";
        case Label.Region: return "Regio";
        case Label.RegionDescription: return "De regio van de game die wordt gespeeld.";
        case Label.Platform: return "Platform";
        case Label.PlatformDescription: return "Het platform waarop de game wordt gespeeld.";
        case Label.UsesEmulator: return "Emulator gebruikt";
        case Label.UsesEmulatorDescription: return "Of er een emulator wordt gebruikt om te spelen.";
        case Label.CustomVariableTooltip: return "Een door jou opgegeven variabele. Deze kan worden weergegeven met de tekstcomponent.";
        case Label.NoVariables: return "Er zijn momenteel geen aangepaste variabelen voor deze game.";
        case Label.NoVariablesWithSpeedrunCom: return "Er zijn momenteel geen speedrun.com‑variabelen of aangepaste variabelen voor deze game.";
        case Label.TimedWithoutLoads: return "worden getimed zonder laadtijden";
        case Label.TimedWithGameTime: return "worden getimed met Game Time";
        case Label.RequireVideoProof: return "vereisen videobewijs";
        case Label.RunsOfThisGamePrefix: return "Runs van deze game ";
        case Label.RunsOfThisGameSuffix: return ".";
        case Label.And: return "en";
        case Label.SetIcon: return "Pictogram instellen";
        case Label.SetIconDescription: return "Kies een afbeeldingsbestand als game‑pictogram. Bepaalde bestandsindelingen werken mogelijk niet overal.";
        case Label.DownloadBoxArt: return "Box‑art downloaden";
        case Label.DownloadBoxArtDescription: return "Probeert box‑art van speedrun.com te downloaden en als game‑pictogram in te stellen.";
        case Label.DownloadIcon: return "Pictogram downloaden";
        case Label.DownloadIconDescription: return "Probeert het pictogram van de game te downloaden van speedrun.com.";
        case Label.RemoveIcon: return "Pictogram verwijderen";
        case Label.RemoveIconDescription: return "Verwijdert het game‑pictogram.";
        case Label.CleaningMenu: return "Opschonen…";
        case Label.ClearOnlyHistory: return "Alleen geschiedenis wissen";
        case Label.ClearOnlyHistoryDescription: return "Splits bewaren de volledige geschiedenis van alle runs, inclusief elke segmenttijd. Je kunt hiermee de geschiedenis wissen. Personal best, beste segmenttijden en vergelijkingen blijven intact.";
        case Label.ClearAllTimes: return "Alle tijden wissen";
        case Label.ClearAllTimesDescription: return "Verwijdert alle tijden uit de splits, inclusief de geschiedenis, zodat de splits volledig leeg zijn.";
        case Label.CleanSumOfBest: return "Som van beste opschonen";
        case Label.CleanSumOfBestDescription: return "Laat je interactief problemen in de segmentgeschiedenis verwijderen die tot een onjuiste som van beste segmenten leiden.";
        case Label.ComparisonsMenu: return "Vergelijkingen…";
        case Label.AddComparison: return "Vergelijking toevoegen";
        case Label.AddComparisonDescription: return "Voegt een nieuwe aangepaste vergelijking toe waarin je tijden kunt opslaan.";
        case Label.ImportComparison: return "Vergelijking importeren";
        case Label.ImportComparisonDescription: return "Importeert de Personal Best van een splits‑bestand als vergelijking.";
        case Label.GenerateGoalComparison: return "Doelvergelijking genereren";
        case Label.GenerateGoalComparisonDescription: return "Genereert een aangepaste doelvergelijking op basis van een doel‑tijd die je opgeeft.";
        case Label.CopyComparison: return "Vergelijking kopiëren";
        case Label.CopyComparisonDescription: return "Maakt een kopie van een bestaande vergelijking.";
        case Label.SetSegmentIcon: return "Pictogram instellen";
        case Label.SetSegmentIconDescription: return "Kies een afbeeldingsbestand als segment‑pictogram. Bepaalde indelingen werken mogelijk niet overal.";
        case Label.RemoveSegmentIcon: return "Pictogram verwijderen";
        case Label.RemoveSegmentIconDescription: return "Verwijdert het segment‑pictogram.";
        case Label.Rename: return "Hernoemen";
        case Label.RenameDescription: return "Kies een nieuwe naam voor de aangepaste vergelijking. Gereserveerde namen of duplicaten zijn niet toegestaan.";
        case Label.CopyAction: return "Kopiëren";
        case Label.CopyDescription: return "Maakt een kopie van de aangepaste vergelijking.";
        case Label.ACopy: return "Kopie";
        case Label.Remove: return "Verwijderen";
        case Label.RemoveDescription: return "Verwijdert de aangepaste vergelijking.";
        case Label.AnyPercent: return "Any%";
        case Label.LowPercent: return "Low%";
        case Label.HundredPercent: return "100%";
        case Label.AddComparisonPrompt: return "Geef de naam van de vergelijking op die je wilt toevoegen:";
        case Label.ComparisonAddError: return "De vergelijking kon niet worden toegevoegd. Mogelijk is de naam duplicaat of gereserveerd.";
        case Label.ImportComparisonPrompt: return "Geef de naam van de vergelijking op die je wilt importeren:";
        case Label.GenerateGoalComparisonPrompt: return "Geef de tijd op die je wilt behalen:";
        case Label.Generate: return "Genereren";
        case Label.GenerateGoalComparisonError: return "Doelvergelijking genereren mislukt. Controleer of de tijd geldig is.";
        case Label.CopyComparisonPrompt: return "Geef de naam van de vergelijking op die je wilt kopiëren:";
        case Label.CopyComparisonError: return "Kopiëren van de vergelijking mislukt. Mogelijk bestaat de vergelijking niet.";
        case Label.NothingToCleanUp: return "Er is niets op te schonen.";
        case Label.CleanPrompt: return "Opschonen?";
        case Label.AssociateRunPrompt: return "Geef de speedrun.com‑ID of URL van de run op:";
        case Label.Associate: return "Koppelen";
        case Label.InvalidSpeedrunUrl: return "Ongeldige speedrun.com‑ID of URL.";
        case Label.AssociateRunError: return "Run koppelen mislukt. De ID is mogelijk ongeldig.";
        case Label.AddVariablePrompt: return "Geef de naam van de aangepaste variabele op die je wilt toevoegen:";
        case Label.RenameComparison: return "Vergelijking hernoemen";
        case Label.RenameComparisonPrompt: return "Geef de nieuwe naam van de vergelijking op:";
        case Label.ComparisonRenameError: return "De vergelijking kon niet worden hernoemd. Mogelijk duplicaat of gereserveerde naam.";
        case Label.GameNotFound: return "Game niet gevonden.";
        case Label.NoBoxArt: return "De game heeft geen box‑art.";
        case Label.DownloadBoxArtError: return "Box‑art downloaden mislukt.";
        case Label.NoGameIcon: return "De game heeft geen pictogram.";
        case Label.DownloadIconError: return "Pictogram downloaden mislukt.";
        case Label.Rank: return "Rang";
        case Label.Player: return "Speler";
        case Label.Time: return "Tijd";
        case Label.Date: return "Datum:";
        case Label.Emulator: return "Emulator";
        case Label.EmulatorTag: return "Emulator";
        case Label.ObsoleteRuns: return "Verouderde runs";
        case Label.Shown: return "Getoond";
        case Label.Hidden: return "Verborgen";
        case Label.OpenLeaderboard: return "Leaderboard openen";
        case Label.Filters: return "Filters";
        case Label.LayoutEditor: return "Lay‑outeditor";
        case Label.Component: return "Component";
        case Label.AddComponent: return "Component toevoegen";
        case Label.RemoveComponent: return "Component verwijderen";
        case Label.DuplicateComponent: return "Component dupliceren";
        case Label.MoveComponentUp: return "Component omhoog";
        case Label.MoveComponentDown: return "Component omlaag";
        case Label.ComponentTitle: return "Titel";
        case Label.ComponentTitleDescription: return "Toont de naam van de game en de categorie, plus eventueel icoon, pogingen en voltooide runs.";
        case Label.ComponentGraph: return "Grafiek";
        case Label.ComponentGraphDescription: return "Visualiseert hoe ver de run voor/achter ligt t.o.v. de vergelijking, met punten per delta.";
        case Label.ComponentSplitsDescription: return "Hoofdcomponent voor split‑tijden met icoon, naam, delta en tijd; bevat scrollen.";
        case Label.ComponentDetailedTimer: return "Gedetailleerde timer";
        case Label.ComponentDetailedTimerDescription: return "Toont totale tijd en segmenttijd, plus optioneel vergelijkingen, icoon en naam.";
        case Label.ComponentTimer: return "Timer";
        case Label.ComponentTimerDescription: return "Toont totale tijd als digitale klok, kleur gebaseerd op vergelijking.";
        case Label.ComponentCurrentComparison: return "Huidige vergelijking";
        case Label.ComponentCurrentComparisonDescription: return "Toont de naam van de huidige vergelijking.";
        case Label.ComponentCurrentPace: return "Huidige pace";
        case Label.ComponentCurrentPaceDescription: return "Voorspelt de eindtijd op basis van de gekozen vergelijking.";
        case Label.ComponentDelta: return "Delta";
        case Label.ComponentDeltaDescription: return "Toont hoeveel je voor/achter ligt t.o.v. de vergelijking.";
        case Label.ComponentPbChance: return "PB‑kans";
        case Label.ComponentPbChanceDescription: return "Toont de kans om PB te halen; verandert tijdens de run.";
        case Label.ComponentPossibleTimeSave: return "Mogelijke tijdbesparing";
        case Label.ComponentPossibleTimeSaveDescription: return "Toont mogelijke besparing op het huidige segment en totaal.";
        case Label.ComponentPreviousSegment: return "Vorig segment";
        case Label.ComponentPreviousSegmentDescription: return "Toont winst/verlies in vorig segment en potentiële besparing; kan Live Segment tonen.";
        case Label.ComponentSegmentTime: return "Segmenttijd";
        case Label.ComponentSegmentTimeDescription: return "Toont segmenttijd voor de gekozen vergelijking; anders huidige vergelijking.";
        case Label.ComponentSumOfBest: return "Som van beste";
        case Label.ComponentSumOfBestDescription: return "Toont de snelst mogelijke eindtijd op basis van historische runs.";
        case Label.ComponentText: return "Tekst";
        case Label.ComponentTextDescription: return "Toont tekst; gecentreerd of links/rechts, of een aangepaste variabele.";
        case Label.ComponentTotalPlaytime: return "Totale speeltijd";
        case Label.ComponentTotalPlaytimeDescription: return "Toont de totale speeltijd van de categorie.";
        case Label.ComponentVariableDescription: return "Maakt een tekstcomponent die de waarde van variabele “{name}” toont.";
        case Label.ComponentBlankSpace: return "Lege ruimte";
        case Label.ComponentBlankSpaceDescription: return "Leeg component voor padding tussen onderdelen.";
        case Label.ComponentSeparator: return "Scheiding";
        case Label.ComponentSeparatorDescription: return "Tekent een scheidingslijn tussen componenten.";
        case Label.AccuracySeconds: return "Seconden";
        case Label.AccuracyTenths: return "Tienden";
        case Label.AccuracyHundredths: return "Honderdsten";
        case Label.AccuracyMilliseconds: return "Milliseconden";
        case Label.FontStyle: return "Stijl";
        case Label.FontWeight: return "Gewicht";
        case Label.FontStretch: return "Rek";
        case Label.FontStyleNormal: return "Normaal";
        case Label.FontStyleItalic: return "Cursief";
        case Label.AlignmentAutomatic: return "Automatisch";
        case Label.AlignmentLeft: return "Links";
        case Label.AlignmentCenter: return "Midden";
        case Label.GradientTransparent: return "Transparant";
        case Label.GradientPlain: return "Effen";
        case Label.GradientVertical: return "Verticaal";
        case Label.GradientHorizontal: return "Horizontaal";
        case Label.GradientAlternating: return "Afwisselend";
        case Label.GradientPlainDelta: return "Effen delta";
        case Label.GradientVerticalDelta: return "Verticale delta";
        case Label.GradientHorizontalDelta: return "Horizontale delta";
        case Label.LayoutBackgroundImage: return "Afbeelding";
        case Label.LayoutBackgroundBrightness: return "Helderheid";
        case Label.LayoutBackgroundOpacity: return "Ondoorzichtigheid";
        case Label.LayoutBackgroundBlur: return "Vervaging";
        case Label.LayoutDirectionVertical: return "Verticaal";
        case Label.LayoutDirectionHorizontal: return "Horizontaal";
        case Label.ColumnKindTime: return "Tijd";
        case Label.ColumnKindVariable: return "Variabele";
        case Label.ColumnStartWithEmpty: return "Leeg";
        case Label.ColumnStartWithComparisonTime: return "Vergelijkingstijd";
        case Label.ColumnStartWithComparisonSegmentTime: return "Vergelijking segmenttijd";
        case Label.ColumnStartWithPossibleTimeSave: return "Mogelijke tijdswinst";
        case Label.ColumnUpdateWithDontUpdate: return "Niet bijwerken";
        case Label.ColumnUpdateWithSplitTime: return "Split‑tijd";
        case Label.ColumnUpdateWithDelta: return "Tijd voor/achter";
        case Label.ColumnUpdateWithDeltaWithFallback: return "Tijd voor/achter of split‑tijd indien leeg";
        case Label.ColumnUpdateWithSegmentTime: return "Segmenttijd";
        case Label.ColumnUpdateWithSegmentDelta: return "Tijd gewonnen/verloren";
        case Label.ColumnUpdateWithSegmentDeltaWithFallback: return "Tijd gewonnen/verloren of segmenttijd indien leeg";
        case Label.ColumnUpdateTriggerOnStartingSegment: return "Bij starten segment";
        case Label.ColumnUpdateTriggerContextual: return "Contextueel";
        case Label.ColumnUpdateTriggerOnEndingSegment: return "Bij einde segment";
        case Label.ComparisonCurrentComparison: return "Huidige vergelijking";
        case Label.CustomVariableNoneAvailable: return "Geen variabelen beschikbaar";
        case Label.CustomVariableNoneAvailableTooltip: return "Aangepaste variabelen kunnen worden gedefinieerd op het tabblad Variabelen bij het bewerken van splits. Extra aangepaste variabelen kunnen automatisch worden geleverd door auto splitters.";
        case Label.HotkeyButtonTooltip: return "Klik om een sneltoets op te nemen. Je kunt ook knoppen op een gamepad gebruiken. Globale sneltoetsen zijn momenteel niet mogelijk. Gamepadknoppen werken globaal.";
        case Label.ServerConnect: return "Verbinden";
        case Label.ServerDisconnect: return "Verbinding verbreken";
        case Label.ServerConnecting: return "Bezig met verbinden...";
        case Label.ServerDisconnecting: return "Bezig met verbreken...";
        case Label.ConnectToServerTitle: return "Verbinden met server";
        case Label.ConnectToServerDescription: return "Geef de WebSocket-URL op:";
        case Label.Connect: return "Verbinden";
        case Label.UpdateAvailable: return "Er is een nieuwe versie van LiveSplit One beschikbaar! Klik hier om opnieuw te laden.";
        case Label.UnsavedChangesBeforeUnload: return "Er zijn niet-opgeslagen wijzigingen. Wil je LiveSplit One echt sluiten?";
        case Label.OpenSidebarAriaLabel: return "Zijbalk openen";
        case Label.FailedToSaveLayout: return "Lay-out opslaan mislukt.";
        case Label.FailedToSaveHotkeys: return "Sneltoetsinstellingen opslaan mislukt.";
        case Label.FailedToSaveGeneralSettings: return "Algemene instellingen opslaan mislukt.";
        case Label.FailedToSaveSplits: return "Splits opslaan mislukt.";
        case Label.LayoutCouldNotBeLoaded: return "De lay-out kon niet worden geladen. Dit is mogelijk geen geldige LiveSplit- of LiveSplit One-lay-out.";
        case Label.EmptySplitsNotSupported: return "Lege splits worden niet ondersteund.";
        case Label.BugEncountered: return "Er is een fout opgetreden:";
        case Label.PleaseReportIssueStart: return "Meld dit probleem ";
        case Label.ReportHere: return "hier";
        case Label.PleaseReportIssueEnd: return ".";
        case Label.BugReportInstructions: return "Om ons te helpen dit probleem op te lossen, voeg de stappen toe om het te reproduceren en voeg de splits en lay‑out toe die je gebruikte toen het probleem optrad.";
        case Label.LoadFailedPrivateBrowsing: return "LiveSplit One kon niet worden geladen.\nMogelijk gebruik je de privé‑modus.\nLiveSplit One kan geen splits, lay‑outs of andere instellingen opslaan door beperkingen van privé‑browsen.\nDeze beperkingen kunnen in de toekomst worden opgeheven.\nOm LiveSplit One nu te gebruiken, schakel privé‑browsen uit in je instellingen.";
        case Label.LoadFailedOutdatedBrowser: return "LiveSplit One kon niet worden geladen.\nMogelijk gebruik je een verouderde browser.\nWerk je browser of iOS‑versie bij en probeer het opnieuw.\nEen andere oorzaak kan een browserextensie zijn, zoals een adblocker, die de toegang tot belangrijke scripts blokkeert.";
    }
}
