import { Label } from ".";

export function resolveEnglish(text: Label): string {
    switch (text) {
        case Label.Ok: return "OK";
        case Label.Cancel: return "Cancel";
        case Label.Settings: return "Settings";
        case Label.Language: return "Language";
        case Label.LanguageDescription: return "Sets the language used in the application.";
        case Label.LanguageAuto: return "Automatic";
        case Label.Theme: return "Theme";
        case Label.ThemeDescription: return "Determines whether to follow the system theme or force a light or dark mode.";
        case Label.ThemeLightMode: return "Light Mode";
        case Label.ThemeDarkMode: return "Dark Mode";
        case Label.HotkeysHeading: return "Hotkeys";
        case Label.GeneralHeading: return "General";
        case Label.NetworkHeading: return "Network";
        case Label.FrameRate: return "Frame Rate";
        case Label.FrameRateDescription: return "Determines the frame rate at which to display the timer. “Battery Aware” tries determining the type of device and charging status to select a good frame rate. “Match Screen” makes the timer match the screen's refresh rate.";
        case Label.FrameRateBatteryAware: return "Battery Aware";
        case Label.FrameRateMatchScreen: return "Match Screen";
        case Label.SaveOnReset: return "Save On Reset";
        case Label.SaveOnResetDescription: return "Determines whether to automatically save the splits when resetting the timer.";
        case Label.ShowControlButtons: return "Show Control Buttons";
        case Label.ShowControlButtonsDescription: return "Determines whether to show buttons beneath the timer that allow controlling it. When disabled, you have to use the hotkeys instead.";
        case Label.ShowManualGameTimeInput: return "Show Manual Game Time Input";
        case Label.ShowManualGameTimeInputDescription: return "Shows a text box beneath the timer that allows you to manually input the game time. You start the timer and do splits by pressing the Enter key in the text box. Make sure to compare against “Game Time”.";
        case Label.ManualGameTimeMode: return "Manual Game Time Mode";
        case Label.ManualGameTimeModeDescription: return "Determines whether to input the manual game time as segment times or split times.";
        case Label.ManualGameTimeModeSegmentTimes: return "Segment Times";
        case Label.ManualGameTimeModeSplitTimes: return "Split Times";
        case Label.AlwaysOnTop: return "Always On Top";
        case Label.AlwaysOnTopDescription: return "Keeps the window always on top of other windows.";
        case Label.SpeedrunComIntegration: return "Speedrun.com Integration";
        case Label.SpeedrunComIntegrationDescription: return "Queries the list of games, categories, and the leaderboards from speedrun.com.";
        case Label.ServerConnection: return "Server Connection";
        case Label.ServerConnectionDescription: return "Allows you to connect to a WebSocket server that can control the timer by sending various commands. The commands are currently a subset of the commands the original LiveSplit supports.";
        case Label.ServerConnectionExperimental: return "This feature is experimental and the protocol will likely change in the future.";
        case Label.TheRunGgIntegration: return "TheRun.gg Integration";
        case Label.TheRunGgIntegrationDescription: return "Integrates with therun.gg for live run tracking and automatic stats uploading. You need an upload key from therun.gg to use this feature.";
        case Label.TheRunGgLiveTracking: return "Live Tracking";
        case Label.TheRunGgLiveTrackingDescription: return "When enabled, live split data is sent to therun.gg after every split action, enabling live run tracking on the website.";
        case Label.TheRunGgStatsUploading: return "Stats Uploading";
        case Label.TheRunGgStatsUploadingDescription: return "When enabled, the splits file is uploaded to therun.gg after every reset or finished run, automatically syncing your runs with the site.";
        case Label.HotkeyAlreadyInUse: return "The hotkey is already in use.";
        case Label.Start: return "Start";
        case Label.Resume: return "Resume";
        case Label.Pause: return "Pause";
        case Label.UndoSplit: return "Undo Split";
        case Label.Reset: return "Reset";
        case Label.SkipSplit: return "Skip Split";
        case Label.ManualGameTimePlaceholder: return "Manual Game Time";
        case Label.LiveSplitLogoAlt: return "LiveSplit Logo";
        case Label.LiveSplitOne: return "LiveSplit One";
        case Label.Splits: return "Splits";
        case Label.Layout: return "Layout";
        case Label.CompareAgainst: return "Compare Against";
        case Label.RealTime: return "Real Time";
        case Label.GameTime: return "Game Time";
        case Label.PopOut: return "Pop Out";
        case Label.About: return "About";
        case Label.Back: return "Back";
        case Label.AboutVersionPrefix: return "Version:";
        case Label.AboutDescription: return "LiveSplit One is a multiplatform version of LiveSplit, the sleek, highly-customizable timer for speedrunners.";
        case Label.AboutViewSource: return "View Source Code on GitHub";
        case Label.AboutRecentChanges: return "Recent Changes";
        case Label.AboutContributors: return "Contributors";
        case Label.Loading: return "Loading...";
        case Label.Add: return "Add";
        case Label.Import: return "Import";
        case Label.OpenSplits: return "Open Splits";
        case Label.EditSplits: return "Edit Splits";
        case Label.ExportSplits: return "Export Splits";
        case Label.CopySplits: return "Copy Splits";
        case Label.RemoveSplits: return "Remove Splits";
        case Label.Untitled: return "Untitled";
        case Label.NoCategory: return "—";
        case Label.DiscardChangesTitle: return "Discard Changes?";
        case Label.DiscardChangesDescription: return "Your current splits are modified and have unsaved changes. Do you want to continue and discard those changes?";
        case Label.DeleteSplitsTitle: return "Delete Splits?";
        case Label.DeleteSplitsDescription: return "Are you sure you want to delete the splits? This operation can not be undone.";
        case Label.SaveBestTimesTitle: return "Save Best Times?";
        case Label.SaveBestTimesDescription: return "You have beaten some of your best times. Do you want to update them?";
        case Label.Yes: return "Yes";
        case Label.No: return "No";
        case Label.DontReset: return "Don't Reset";
        case Label.FailedToExportSplits: return "Failed to export the splits.";
        case Label.CantImportEmptySplits: return "Can't import empty splits.";
        case Label.FailedToReadFile: return "Failed to read the file:";
        case Label.FailedToImportSplits: return "Failed to import the splits:";
        case Label.CouldNotParseSplits: return "Couldn't parse the splits.";
        case Label.LoadedSplitsInvalid: return "The loaded splits are invalid.";
        case Label.NewSegmentName: return "Time";
        case Label.EditWhileRunningError: return "You can't edit your splits while the timer is running.";
        case Label.Edit: return "Edit";
        case Label.Save: return "Save";
        case Label.Export: return "Export";
        case Label.FailedToParseTimeSpan: return "Failed to parse TimeSpan";
        case Label.Default: return "Default";
        case Label.Game: return "Game";
        case Label.Category: return "Category";
        case Label.StartTimerAt: return "Start Timer At";
        case Label.Attempts: return "Attempts";
        case Label.SplitsEditor: return "Splits Editor";
        case Label.Variables: return "Variables";
        case Label.Rules: return "Rules";
        case Label.Leaderboard: return "Leaderboard";
        case Label.InsertAbove: return "Insert Above";
        case Label.InsertBelow: return "Insert Below";
        case Label.RemoveSegment: return "Remove Segment";
        case Label.MoveUp: return "Move Up";
        case Label.MoveDown: return "Move Down";
        case Label.AddVariable: return "Add Variable";
        case Label.OpenPbPage: return "Open PB Page";
        case Label.AssociateRun: return "Associate Run";
        case Label.Icon: return "Icon";
        case Label.SegmentName: return "Segment Name";
        case Label.SplitTime: return "Split Time";
        case Label.SegmentTime: return "Segment Time";
        case Label.BestSegment: return "Best Segment";
        case Label.SpeedrunComVariableTooltip: return "A variable on speedrun.com specific to the game.";
        case Label.Region: return "Region";
        case Label.RegionDescription: return "The region of the game that is being played.";
        case Label.Platform: return "Platform";
        case Label.PlatformDescription: return "The platform that the game is being played on.";
        case Label.UsesEmulator: return "Uses Emulator";
        case Label.UsesEmulatorDescription: return "Whether an emulator is being used to play the game.";
        case Label.CustomVariableTooltip: return "A custom variable specified by you. These can be displayed with the text component.";
        case Label.NoVariables: return "There are currently no custom variables for this game.";
        case Label.NoVariablesWithSpeedrunCom: return "There are currently no Speedrun.com variables or custom variables for this game.";
        case Label.TimedWithoutLoads: return "are timed without the loading times";
        case Label.TimedWithGameTime: return "are timed with Game Time";
        case Label.RequireVideoProof: return "require video proof";
        case Label.RunsOfThisGamePrefix: return "Runs of this game ";
        case Label.RunsOfThisGameSuffix: return ".";
        case Label.And: return "and";
        case Label.SetIcon: return "Set Icon";
        case Label.SetIconDescription: return "Allows you to choose an image file to set as the game's icon. Certain file formats may not work everywhere.";
        case Label.DownloadBoxArt: return "Download Box Art";
        case Label.DownloadBoxArtDescription: return "Attempts to download the box art of the game from speedrun.com, to set as the game's icon.";
        case Label.DownloadIcon: return "Download Icon";
        case Label.DownloadIconDescription: return "Attempts to download the icon of the game from speedrun.com.";
        case Label.RemoveIcon: return "Remove Icon";
        case Label.RemoveIconDescription: return "Removes the icon of the game.";
        case Label.CleaningMenu: return "Cleaning…";
        case Label.ClearOnlyHistory: return "Clear Only History";
        case Label.ClearOnlyHistoryDescription: return "Splits store the entire history of all runs, including every segment time. This information is used by various components. You can clear the history with this. The personal best, the best segment times, and the comparisons will not be affected.";
        case Label.ClearAllTimes: return "Clear All Times";
        case Label.ClearAllTimesDescription: return "This removes all the times from the splits, including all the history, such that the splits are completely empty, as if they were just created.";
        case Label.CleanSumOfBest: return "Clean Sum of Best";
        case Label.CleanSumOfBestDescription: return "Allows you to interactively remove potential issues in the segment history that lead to an inaccurate Sum of Best Segments. If you skip a split, whenever you will do the next split, the combined segment time might be faster than the sum of the individual best segments. This will point out all such occurrences and allow you to delete them individually if any of them seem wrong.";
        case Label.ComparisonsMenu: return "Comparisons…";
        case Label.AddComparison: return "Add Comparison";
        case Label.AddComparisonDescription: return "Adds a new custom comparison where you can store any times that you would like.";
        case Label.ImportComparison: return "Import Comparison";
        case Label.ImportComparisonDescription: return "Imports the Personal Best of a splits file you provide as a comparison.";
        case Label.GenerateGoalComparison: return "Generate Goal Comparison";
        case Label.GenerateGoalComparisonDescription: return "Generates a custom goal comparison based on a goal time that you can specify. The comparison's times are automatically balanced based on the segment history such that it roughly represents what the split times for the goal time would look like. Since it is populated by the segment history, the goal times are capped to a range between the sum of the best segments and the sum of the worst segments. The comparison is only populated for the selected timing method. The other timing method's comparison times are not modified by this, so you can generate it again with the other timing method to generate the comparison times for both timing methods.";
        case Label.CopyComparison: return "Copy Comparison";
        case Label.CopyComparisonDescription: return "Copies any existing comparison, including the Personal Best or even any other automatically provided comparison as a new custom comparison. You could for example use this to keep the Latest Run around as a comparison that exists for as long as you want it to.";
        case Label.SetSegmentIcon: return "Set Icon";
        case Label.SetSegmentIconDescription: return "Allows you to choose an image file to set as the segment's icon. Certain file formats may not work everywhere.";
        case Label.RemoveSegmentIcon: return "Remove Icon";
        case Label.RemoveSegmentIconDescription: return "Removes the segment's icon.";
        case Label.Rename: return "Rename";
        case Label.RenameDescription: return "Choose a new name for the custom comparison. There are reserved names that can't be used. You also can't have duplicate names.";
        case Label.CopyAction: return "Copy";
        case Label.CopyDescription: return "Creates a copy of the custom comparison.";
        case Label.ACopy: return "Copy";
        case Label.Remove: return "Remove";
        case Label.RemoveDescription: return "Removes the custom comparison.";
        case Label.AnyPercent: return "Any%";
        case Label.LowPercent: return "Low%";
        case Label.HundredPercent: return "100%";
        case Label.AddComparisonPrompt: return "Specify the name of the comparison you want to add:";
        case Label.ComparisonAddError: return "The comparison could not be added. It may be a duplicate or a reserved name.";
        case Label.ImportComparisonPrompt: return "Specify the name of the comparison you want to import:";
        case Label.GenerateGoalComparisonPrompt: return "Specify the time you want to achieve:";
        case Label.Generate: return "Generate";
        case Label.GenerateGoalComparisonError: return "Failed generating the goal comparison. Make sure to specify a valid time.";
        case Label.CopyComparisonPrompt: return "Specify the name of the comparison you want to copy:";
        case Label.CopyComparisonError: return "Failed copying the comparison. The comparison may not exist.";
        case Label.NothingToCleanUp: return "There is nothing to clean up.";
        case Label.CleanPrompt: return "Clean?";
        case Label.AssociateRunPrompt: return "Specify the speedrun.com ID or URL of the run:";
        case Label.Associate: return "Associate";
        case Label.InvalidSpeedrunUrl: return "Invalid speedrun.com ID or URL.";
        case Label.AssociateRunError: return "Couldn't associate the run. The ID may be invalid.";
        case Label.AddVariablePrompt: return "Specify the name of the custom variable you want to add:";
        case Label.RenameComparison: return "Rename Comparison";
        case Label.RenameComparisonPrompt: return "Specify the new name of the comparison:";
        case Label.ComparisonRenameError: return "The comparison could not be renamed. It may be a duplicate or a reserved name.";
        case Label.GameNotFound: return "Couldn't find the game.";
        case Label.NoBoxArt: return "The game doesn't have a box art.";
        case Label.DownloadBoxArtError: return "Couldn't download the box art.";
        case Label.NoGameIcon: return "The game doesn't have an icon.";
        case Label.DownloadIconError: return "Couldn't download the icon.";
        case Label.Rank: return "Rank";
        case Label.Player: return "Player";
        case Label.Time: return "Time";
        case Label.Date: return "Date:";
        case Label.Emulator: return "Emulator";
        case Label.EmulatorTag: return "Emulator";
        case Label.ObsoleteRuns: return "Obsolete Runs";
        case Label.Shown: return "Shown";
        case Label.Hidden: return "Hidden";
        case Label.OpenLeaderboard: return "Open Leaderboard";
        case Label.Filters: return "Filters";
        case Label.LayoutEditor: return "Layout Editor";
        case Label.Component: return "Component";
        case Label.AddComponent: return "Add Component";
        case Label.RemoveComponent: return "Remove Component";
        case Label.DuplicateComponent: return "Duplicate Component";
        case Label.MoveComponentUp: return "Move Component Up";
        case Label.MoveComponentDown: return "Move Component Down";
        case Label.ComponentTitle: return "Title";
        case Label.ComponentTitleDescription: return "Shows the name of the game and the category that is being run. Additionally, the game icon, the attempt count, and the total number of successfully finished runs can be shown.";
        case Label.ComponentGraph: return "Graph";
        case Label.ComponentGraphDescription: return "Visualizes how far the current run has been ahead or behind the chosen comparison throughout the whole run. All the individual deltas are shown as points on the graph.";
        case Label.ComponentSplitsDescription: return "The main component for visualizing all the split times. Each segment is shown in a tabular fashion showing the segment icon, segment name, the delta compared to the chosen comparison, and the split time. The list provides scrolling functionality, so not every segment needs to be shown all the time.";
        case Label.ComponentDetailedTimer: return "Detailed Timer";
        case Label.ComponentDetailedTimerDescription: return "Shows two timers, one for the total time of the current run and one showing the time of just the current segment. Other information, like segment times of up to two comparisons, the segment icon, and the segment name, can also be shown.";
        case Label.ComponentTimer: return "Timer";
        case Label.ComponentTimerDescription: return "Shows the total time of the current run as a digital clock. The color of the time shown is based on how well the current run is doing compared to the chosen comparison.";
        case Label.ComponentCurrentComparison: return "Current Comparison";
        case Label.ComponentCurrentComparisonDescription: return "Shows the name of the comparison that the timer is currently comparing against.";
        case Label.ComponentCurrentPace: return "Current Pace";
        case Label.ComponentCurrentPaceDescription: return "Shows a prediction for the current run's final time. The remainder of the run is predicted based on the chosen comparison for the component. For example, the “Best Segments” comparison can be chosen to show the best possible final time for the current run based on the Sum of Best Segments.";
        case Label.ComponentDelta: return "Delta";
        case Label.ComponentDeltaDescription: return "Shows how far ahead or behind the current run is compared to the chosen comparison.";
        case Label.ComponentPbChance: return "PB Chance";
        case Label.ComponentPbChanceDescription: return "Shows how likely it is for the active run to beat the personal best. If there is no active run, it shows the general chance of beating the personal best. During a run, it actively changes based on how well the run is going.";
        case Label.ComponentPossibleTimeSave: return "Possible Time Save";
        case Label.ComponentPossibleTimeSaveDescription: return "Shows how much time you can save on the current segment compared to the chosen comparison, based on the best segment time of the segment. This component also allows showing the “Total Possible Time Save” for the remainder of the current run.";
        case Label.ComponentPreviousSegment: return "Previous Segment";
        case Label.ComponentPreviousSegmentDescription: return "Shows how much time was saved or lost during the previous segment based on the chosen comparison. Additionally, the potential time save for the previous segment can be displayed. This component switches to a “Live Segment” view that shows the active time loss whenever you are losing time on the current segment.";
        case Label.ComponentSegmentTime: return "Segment Time";
        case Label.ComponentSegmentTimeDescription: return "Shows the time for the current segment for the chosen comparison. If no comparison is specified it uses the timer's current comparison.";
        case Label.ComponentSumOfBest: return "Sum of Best";
        case Label.ComponentSumOfBestDescription: return "Shows the fastest possible time to complete a run of the current category, based on information collected from all the previous runs. This often matches up with the sum of the best segment times of all the segments, but that may not always be the case, as skipped segments may introduce combined segments that may be faster than the actual sum of their best segment times. The name is therefore a bit misleading, but sticks around for historical reasons.";
        case Label.ComponentText: return "Text";
        case Label.ComponentTextDescription: return "Shows the text that you specify. This can either be a single centered text, or split up into a left and right text, which is suitable for a situation where you have a label and a value. There is also the option of showing a custom variable that you specify in the splits editor.";
        case Label.ComponentTotalPlaytime: return "Total Playtime";
        case Label.ComponentTotalPlaytimeDescription: return "Shows the total amount of time that the current category has been played for.";
        case Label.ComponentVariableDescription: return "Creates a text component that shows the value of the custom variable “{name}”.";
        case Label.ComponentBlankSpace: return "Blank Space";
        case Label.ComponentBlankSpaceDescription: return "An empty component that doesn't show anything other than a background. It mostly serves as padding between other components.";
        case Label.ComponentSeparator: return "Separator";
        case Label.ComponentSeparatorDescription: return "A simple component that just renders a separator between components.";
        case Label.AccuracySeconds: return "Seconds";
        case Label.AccuracyTenths: return "Tenths";
        case Label.AccuracyHundredths: return "Hundredths";
        case Label.AccuracyMilliseconds: return "Milliseconds";
        case Label.FontStyle: return "Style";
        case Label.FontWeight: return "Weight";
        case Label.FontStretch: return "Stretch";
        case Label.FontStyleNormal: return "Normal";
        case Label.FontStyleItalic: return "Italic";
        case Label.AlignmentAutomatic: return "Automatic";
        case Label.AlignmentLeft: return "Left";
        case Label.AlignmentCenter: return "Center";
        case Label.GradientTransparent: return "Transparent";
        case Label.GradientPlain: return "Plain";
        case Label.GradientVertical: return "Vertical";
        case Label.GradientHorizontal: return "Horizontal";
        case Label.GradientAlternating: return "Alternating";
        case Label.GradientPlainDelta: return "Plain Delta";
        case Label.GradientVerticalDelta: return "Vertical Delta";
        case Label.GradientHorizontalDelta: return "Horizontal Delta";
        case Label.LayoutBackgroundImage: return "Image";
        case Label.LayoutBackgroundBrightness: return "Brightness";
        case Label.LayoutBackgroundOpacity: return "Opacity";
        case Label.LayoutBackgroundBlur: return "Blur";
        case Label.LayoutDirectionVertical: return "Vertical";
        case Label.LayoutDirectionHorizontal: return "Horizontal";
        case Label.ColumnKindTime: return "Time";
        case Label.ColumnKindVariable: return "Variable";
        case Label.ColumnStartWithEmpty: return "Empty";
        case Label.ColumnStartWithComparisonTime: return "Comparison Time";
        case Label.ColumnStartWithComparisonSegmentTime: return "Comparison Segment Time";
        case Label.ColumnStartWithPossibleTimeSave: return "Possible Time Save";
        case Label.ColumnUpdateWithDontUpdate: return "Don't Update";
        case Label.ColumnUpdateWithSplitTime: return "Split Time";
        case Label.ColumnUpdateWithDelta: return "Time Ahead / Behind";
        case Label.ColumnUpdateWithDeltaWithFallback: return "Time Ahead / Behind or Split Time If Empty";
        case Label.ColumnUpdateWithSegmentTime: return "Segment Time";
        case Label.ColumnUpdateWithSegmentDelta: return "Time Saved / Lost";
        case Label.ColumnUpdateWithSegmentDeltaWithFallback: return "Time Saved / Lost or Segment Time If Empty";
        case Label.ColumnUpdateTriggerOnStartingSegment: return "On Starting Segment";
        case Label.ColumnUpdateTriggerContextual: return "Contextual";
        case Label.ColumnUpdateTriggerOnEndingSegment: return "On Ending Segment";
        case Label.ComparisonCurrentComparison: return "Current Comparison";
        case Label.CustomVariableNoneAvailable: return "No variables available";
        case Label.CustomVariableNoneAvailableTooltip: return "Custom variables can be defined in the Variables tab when editing splits. Additional custom variables can be provided automatically by auto splitters.";
        case Label.HotkeyButtonTooltip: return "Click to record a hotkey. You may also use buttons on a gamepad. Global hotkeys are currently not possible. Gamepad buttons work globally.";
        case Label.ServerConnect: return "Connect";
        case Label.ServerDisconnect: return "Disconnect";
        case Label.ServerConnecting: return "Connecting...";
        case Label.ServerDisconnecting: return "Disconnecting...";
        case Label.ConnectToServerTitle: return "Connect to Server";
        case Label.ConnectToServerDescription: return "Specify the WebSocket URL:";
        case Label.Connect: return "Connect";
        case Label.UpdateAvailable: return "A new version of LiveSplit One is available! Click here to reload.";
        case Label.UnsavedChangesBeforeUnload: return "There are unsaved changes. Do you really want to close LiveSplit One?";
        case Label.OpenSidebarAriaLabel: return "Open Sidebar";
        case Label.FailedToSaveLayout: return "Failed to save the layout.";
        case Label.FailedToSaveHotkeys: return "Failed to save the hotkey settings.";
        case Label.FailedToSaveGeneralSettings: return "Failed to save the general settings.";
        case Label.FailedToSaveSplits: return "Failed to save the splits.";
        case Label.LayoutCouldNotBeLoaded: return "The layout could not be loaded. This may not be a valid LiveSplit or LiveSplit One Layout.";
        case Label.EmptySplitsNotSupported: return "Empty Splits are not supported.";
        case Label.BugEncountered: return "You encountered a bug:";
        case Label.PleaseReportIssueStart: return "Please report this issue ";
        case Label.ReportHere: return "here";
        case Label.PleaseReportIssueEnd: return ".";
        case Label.BugReportInstructions: return "In order to help us fix this issue, please include steps to reproduce it and attach the splits and layout you were using when the issue occurred.";
        case Label.LoadFailedPrivateBrowsing: return "Couldn't load LiveSplit One.\nYou may be in private browsing mode.\nLiveSplit One cannot store any splits, layouts, or other settings because of the limitations of the browser's private browsing mode.\nThese limitations may be lifted in the future.\nTo run LiveSplit One for now, please disable private browsing in your settings.";
        case Label.LoadFailedOutdatedBrowser: return "Couldn't load LiveSplit One.\nYou may be using a browser that is not up to date.\nPlease update your browser or your iOS version and try again.\nAnother reason might be that a browser extension, such as an adblocker, is blocking access to important scripts.";
    }
}
