import { Label } from ".";

export function resolveGerman(text: Label): string {
    switch (text) {
        case Label.Ok: return "OK";
        case Label.Cancel: return "Abbrechen";
        case Label.Settings: return "Einstellungen";
        case Label.Language: return "Sprache";
        case Label.LanguageDescription: return "Legt die in der Anwendung verwendete Sprache fest.";
        case Label.LanguageAuto: return "Automatisch";
        case Label.Theme: return "Design";
        case Label.ThemeDescription: return "Legt fest, ob das Systemdesign übernommen oder der helle bzw. dunkle Modus erzwungen wird.";
        case Label.ThemeLightMode: return "Heller Modus";
        case Label.ThemeDarkMode: return "Dunkler Modus";
        case Label.HotkeysHeading: return "Tastenkürzel";
        case Label.GeneralHeading: return "Allgemein";
        case Label.NetworkHeading: return "Netzwerk";
        case Label.FrameRate: return "Bildwiederholrate";
        case Label.FrameRateDescription: return "Legt fest, mit welcher Bildwiederholrate der Timer angezeigt wird. „Batteriebewusst“ versucht anhand des Gerätetyps und des Ladestatus eine gute Bildwiederholrate zu wählen. „An Bildschirm anpassen“ lässt den Timer der Bildwiederholrate des Bildschirms entsprechen.";
        case Label.FrameRateBatteryAware: return "Batteriebewusst";
        case Label.FrameRateMatchScreen: return "An Bildschirm anpassen";
        case Label.SaveOnReset: return "Beim Zurücksetzen speichern";
        case Label.SaveOnResetDescription: return "Legt fest, ob die Splits beim Zurücksetzen des Timers automatisch gespeichert werden.";
        case Label.ShowControlButtons: return "Steuerungsbuttons anzeigen";
        case Label.ShowControlButtonsDescription: return "Legt fest, ob unter dem Timer Schaltflächen angezeigt werden, mit denen er gesteuert werden kann. Wenn deaktiviert, müssen die Hotkeys verwendet werden.";
        case Label.ShowManualGameTimeInput: return "Manuelle Spielzeit‑Eingabe anzeigen";
        case Label.ShowManualGameTimeInputDescription: return "Zeigt ein Textfeld unter dem Timer an, mit dem du die Spielzeit manuell eingeben kannst. Du startest den Timer und machst Splits, indem du im Textfeld die Eingabetaste drückst. Vergleiche mit „Spielzeit“.";
        case Label.ManualGameTimeMode: return "Manueller Spielzeitmodus";
        case Label.ManualGameTimeModeDescription: return "Legt fest, ob die manuelle Spielzeit als Segmentzeiten oder Splitzeiten eingegeben wird.";
        case Label.ManualGameTimeModeSegmentTimes: return "Segmentzeiten";
        case Label.ManualGameTimeModeSplitTimes: return "Splitzeiten";
        case Label.AlwaysOnTop: return "Immer im Vordergrund";
        case Label.AlwaysOnTopDescription: return "Hält das Fenster immer über anderen Fenstern.";
        case Label.SpeedrunComIntegration: return "Speedrun.com‑Integration";
        case Label.SpeedrunComIntegrationDescription: return "Fragt die Liste der Spiele, Kategorien und Bestenlisten von speedrun.com ab.";
        case Label.ServerConnection: return "Serververbindung";
        case Label.ServerConnectionDescription: return "Ermöglicht die Verbindung zu einem WebSocket‑Server, der den Timer durch das Senden verschiedener Befehle steuern kann. Die Befehle sind derzeit eine Teilmenge der Befehle, die das ursprüngliche LiveSplit unterstützt.";
        case Label.ServerConnectionExperimental: return "Diese Funktion ist experimentell und das Protokoll wird sich wahrscheinlich in Zukunft ändern.";
        case Label.TheRunGgIntegration: return "TheRun.gg-Integration";
        case Label.TheRunGgIntegrationDescription: return "Integriert sich mit therun.gg für Live-Run-Tracking und automatisches Hochladen von Statistiken. Für diese Funktion benötigst du einen Upload-Schlüssel von therun.gg.";
        case Label.TheRunGgLiveTracking: return "Live-Tracking";
        case Label.TheRunGgLiveTrackingDescription: return "Wenn aktiviert, werden Live-Split-Daten nach jeder Split-Aktion an therun.gg gesendet, sodass der Run live auf der Website verfolgt werden kann.";
        case Label.TheRunGgStatsUploading: return "Statistik-Upload";
        case Label.TheRunGgStatsUploadingDescription: return "Wenn aktiviert, wird die Splits-Datei nach jedem Reset oder abgeschlossenen Run zu therun.gg hochgeladen und deine Runs werden automatisch mit der Website synchronisiert.";
        case Label.HotkeyAlreadyInUse: return "Der Hotkey wird bereits verwendet.";
        case Label.Start: return "Start";
        case Label.Resume: return "Fortsetzen";
        case Label.Pause: return "Pause";
        case Label.UndoSplit: return "Split rückgängig";
        case Label.Reset: return "Zurücksetzen";
        case Label.SkipSplit: return "Split überspringen";
        case Label.ManualGameTimePlaceholder: return "Manuelle Spielzeit";
        case Label.LiveSplitLogoAlt: return "LiveSplit‑Logo";
        case Label.LiveSplitOne: return "LiveSplit One";
        case Label.Splits: return "Splits";
        case Label.Layout: return "Layout";
        case Label.CompareAgainst: return "Vergleichen mit";
        case Label.RealTime: return "Echtzeit";
        case Label.GameTime: return "Spielzeit";
        case Label.PopOut: return "Pop‑out";
        case Label.About: return "Über";
        case Label.Back: return "Zurück";
        case Label.AboutVersionPrefix: return "Version:";
        case Label.AboutDescription: return "LiveSplit One ist eine plattformübergreifende Version von LiveSplit, dem schlanken und hochgradig anpassbaren Timer für Speedrunner.";
        case Label.AboutViewSource: return "Quellcode auf GitHub ansehen";
        case Label.AboutRecentChanges: return "Neueste Änderungen";
        case Label.AboutContributors: return "Mitwirkende";
        case Label.Loading: return "Wird geladen...";
        case Label.Add: return "Hinzufügen";
        case Label.Import: return "Importieren";
        case Label.OpenSplits: return "Splits öffnen";
        case Label.EditSplits: return "Splits bearbeiten";
        case Label.ExportSplits: return "Splits exportieren";
        case Label.CopySplits: return "Splits kopieren";
        case Label.RemoveSplits: return "Splits entfernen";
        case Label.Untitled: return "Unbenannt";
        case Label.NoCategory: return "—";
        case Label.DiscardChangesTitle: return "Änderungen verwerfen?";
        case Label.DiscardChangesDescription: return "Deine aktuellen Splits wurden geändert und enthalten nicht gespeicherte Änderungen. Möchtest du fortfahren und diese Änderungen verwerfen?";
        case Label.DeleteSplitsTitle: return "Splits löschen?";
        case Label.DeleteSplitsDescription: return "Möchtest du die Splits wirklich löschen? Dieser Vorgang kann nicht rückgängig gemacht werden.";
        case Label.SaveBestTimesTitle: return "Bestzeiten speichern?";
        case Label.SaveBestTimesDescription: return "Du hast einige deiner Bestzeiten unterboten. Möchtest du sie aktualisieren?";
        case Label.Yes: return "Ja";
        case Label.No: return "Nein";
        case Label.DontReset: return "Nicht zurücksetzen";
        case Label.FailedToExportSplits: return "Splits konnten nicht exportiert werden.";
        case Label.CantImportEmptySplits: return "Leere Splits können nicht importiert werden.";
        case Label.FailedToReadFile: return "Datei konnte nicht gelesen werden:";
        case Label.FailedToImportSplits: return "Splits konnten nicht importiert werden:";
        case Label.CouldNotParseSplits: return "Splits konnten nicht geparst werden.";
        case Label.LoadedSplitsInvalid: return "Die geladenen Splits sind ungültig.";
        case Label.NewSegmentName: return "Zeit";
        case Label.EditWhileRunningError: return "Du kannst deine Splits nicht bearbeiten, während der Timer läuft.";
        case Label.Edit: return "Bearbeiten";
        case Label.Save: return "Speichern";
        case Label.Export: return "Exportieren";
        case Label.FailedToParseTimeSpan: return "TimeSpan konnte nicht geparst werden";
        case Label.Default: return "Standard";
        case Label.Game: return "Spiel";
        case Label.Category: return "Kategorie";
        case Label.StartTimerAt: return "Timer starten bei";
        case Label.Attempts: return "Versuche";
        case Label.SplitsEditor: return "Splits‑Editor";
        case Label.Variables: return "Variablen";
        case Label.Rules: return "Regeln";
        case Label.Leaderboard: return "Rangliste";
        case Label.InsertAbove: return "Darüber einfügen";
        case Label.InsertBelow: return "Darunter einfügen";
        case Label.RemoveSegment: return "Segment entfernen";
        case Label.MoveUp: return "Nach oben";
        case Label.MoveDown: return "Nach unten";
        case Label.AddVariable: return "Variable hinzufügen";
        case Label.OpenPbPage: return "PB‑Seite öffnen";
        case Label.AssociateRun: return "Run verknüpfen";
        case Label.Icon: return "Symbol";
        case Label.SegmentName: return "Segmentname";
        case Label.SplitTime: return "Splitzeit";
        case Label.SegmentTime: return "Segmentzeit";
        case Label.BestSegment: return "Bestes Segment";
        case Label.SpeedrunComVariableTooltip: return "Eine speedrun.com‑Variable, die zum Spiel gehört.";
        case Label.Region: return "Region";
        case Label.RegionDescription: return "Die Region des gespielten Spiels.";
        case Label.Platform: return "Plattform";
        case Label.PlatformDescription: return "Die Plattform, auf der das Spiel gespielt wird.";
        case Label.UsesEmulator: return "Emulator verwenden";
        case Label.UsesEmulatorDescription: return "Ob ein Emulator zum Spielen verwendet wird.";
        case Label.CustomVariableTooltip: return "Eine von dir definierte Variable. Diese kann im Text‑Komponent angezeigt werden.";
        case Label.NoVariables: return "Derzeit gibt es keine benutzerdefinierten Variablen für dieses Spiel.";
        case Label.NoVariablesWithSpeedrunCom: return "Derzeit gibt es keine speedrun.com‑Variablen oder benutzerdefinierten Variablen für dieses Spiel.";
        case Label.TimedWithoutLoads: return "werden ohne Ladezeiten getimt";
        case Label.TimedWithGameTime: return "werden mit Spielzeit getimt";
        case Label.RequireVideoProof: return "erfordern einen Videobeweis";
        case Label.RunsOfThisGamePrefix: return "Runs dieses Spiels ";
        case Label.RunsOfThisGameSuffix: return ".";
        case Label.And: return "und";
        case Label.SetIcon: return "Symbol festlegen";
        case Label.SetIconDescription: return "Wähle eine Bilddatei als Spielsymbol. Manche Formate funktionieren nicht überall.";
        case Label.DownloadBoxArt: return "Cover herunterladen";
        case Label.DownloadBoxArtDescription: return "Versucht, das Cover von speedrun.com herunterzuladen und als Spielsymbol zu setzen.";
        case Label.DownloadIcon: return "Symbol herunterladen";
        case Label.DownloadIconDescription: return "Versucht, das Symbol des Spiels von speedrun.com herunterzuladen.";
        case Label.RemoveIcon: return "Symbol entfernen";
        case Label.RemoveIconDescription: return "Entfernt das Spielsymbol.";
        case Label.CleaningMenu: return "Bereinigen…";
        case Label.ClearOnlyHistory: return "Nur Verlauf löschen";
        case Label.ClearOnlyHistoryDescription: return "Splits speichern den gesamten Verlauf aller Runs. Damit kannst du den Verlauf löschen, ohne PB, beste Segmente oder Vergleiche zu beeinflussen.";
        case Label.ClearAllTimes: return "Alle Zeiten löschen";
        case Label.ClearAllTimesDescription: return "Entfernt alle Zeiten inklusive Verlauf, sodass die Splits komplett leer sind.";
        case Label.CleanSumOfBest: return "Summe der Besten bereinigen";
        case Label.CleanSumOfBestDescription: return "Ermöglicht das interaktive Entfernen von Problemen in der Segmenthistorie, die eine ungenaue Summe der besten Segmente verursachen.";
        case Label.ComparisonsMenu: return "Vergleiche…";
        case Label.AddComparison: return "Vergleich hinzufügen";
        case Label.AddComparisonDescription: return "Fügt einen benutzerdefinierten Vergleich hinzu, in dem du Zeiten speichern kannst.";
        case Label.ImportComparison: return "Vergleich importieren";
        case Label.ImportComparisonDescription: return "Importiert die Personal Best aus einer Splits‑Datei als Vergleich.";
        case Label.GenerateGoalComparison: return "Zielvergleich erzeugen";
        case Label.GenerateGoalComparisonDescription: return "Erzeugt einen Zielvergleich basierend auf einer Zielzeit.";
        case Label.CopyComparison: return "Vergleich kopieren";
        case Label.CopyComparisonDescription: return "Kopiert einen vorhandenen Vergleich als neuen benutzerdefinierten Vergleich.";
        case Label.SetSegmentIcon: return "Symbol festlegen";
        case Label.SetSegmentIconDescription: return "Wähle eine Bilddatei als Segmentsymbol. Manche Formate funktionieren nicht überall.";
        case Label.RemoveSegmentIcon: return "Symbol entfernen";
        case Label.RemoveSegmentIconDescription: return "Entfernt das Segmentsymbol.";
        case Label.Rename: return "Umbenennen";
        case Label.RenameDescription: return "Wähle einen neuen Namen für den benutzerdefinierten Vergleich. Reservierte Namen oder Duplikate sind nicht erlaubt.";
        case Label.CopyAction: return "Kopieren";
        case Label.CopyDescription: return "Erstellt eine Kopie des benutzerdefinierten Vergleichs.";
        case Label.ACopy: return "Kopie";
        case Label.Remove: return "Entfernen";
        case Label.RemoveDescription: return "Entfernt den benutzerdefinierten Vergleich.";
        case Label.AnyPercent: return "Any%";
        case Label.LowPercent: return "Low%";
        case Label.HundredPercent: return "100%";
        case Label.AddComparisonPrompt: return "Gib den Namen des Vergleichs an, den du hinzufügen möchtest:";
        case Label.ComparisonAddError: return "Der Vergleich konnte nicht hinzugefügt werden. Möglicherweise Duplikat oder reservierter Name.";
        case Label.ImportComparisonPrompt: return "Gib den Namen des Vergleichs an, den du importieren möchtest:";
        case Label.GenerateGoalComparisonPrompt: return "Gib die Zeit an, die du erreichen möchtest:";
        case Label.Generate: return "Erzeugen";
        case Label.GenerateGoalComparisonError: return "Zielvergleich konnte nicht erzeugt werden. Bitte eine gültige Zeit angeben.";
        case Label.CopyComparisonPrompt: return "Gib den Namen des Vergleichs an, den du kopieren möchtest:";
        case Label.CopyComparisonError: return "Vergleich konnte nicht kopiert werden. Er existiert möglicherweise nicht.";
        case Label.NothingToCleanUp: return "Es gibt nichts zu bereinigen.";
        case Label.CleanPrompt: return "Bereinigen?";
        case Label.AssociateRunPrompt: return "Gib die speedrun.com‑ID oder URL des Runs an:";
        case Label.Associate: return "Verknüpfen";
        case Label.InvalidSpeedrunUrl: return "Ungültige speedrun.com‑ID oder URL.";
        case Label.AssociateRunError: return "Run konnte nicht verknüpft werden. Die ID ist möglicherweise ungültig.";
        case Label.AddVariablePrompt: return "Gib den Namen der benutzerdefinierten Variable an, die du hinzufügen möchtest:";
        case Label.RenameComparison: return "Vergleich umbenennen";
        case Label.RenameComparisonPrompt: return "Gib den neuen Namen des Vergleichs an:";
        case Label.ComparisonRenameError: return "Der Vergleich konnte nicht umbenannt werden. Möglicherweise Duplikat oder reservierter Name.";
        case Label.GameNotFound: return "Spiel nicht gefunden.";
        case Label.NoBoxArt: return "Das Spiel hat kein Cover.";
        case Label.DownloadBoxArtError: return "Cover konnte nicht heruntergeladen werden.";
        case Label.NoGameIcon: return "Das Spiel hat kein Symbol.";
        case Label.DownloadIconError: return "Symbol konnte nicht heruntergeladen werden.";
        case Label.Rank: return "Rang";
        case Label.Player: return "Spieler";
        case Label.Time: return "Zeit";
        case Label.Date: return "Datum:";
        case Label.Emulator: return "Emulator";
        case Label.EmulatorTag: return "Emulator";
        case Label.ObsoleteRuns: return "Veraltete Runs";
        case Label.Shown: return "Angezeigt";
        case Label.Hidden: return "Ausgeblendet";
        case Label.OpenLeaderboard: return "Rangliste öffnen";
        case Label.Filters: return "Filter";
        case Label.LayoutEditor: return "Layout‑Editor";
        case Label.Component: return "Komponente";
        case Label.AddComponent: return "Komponente hinzufügen";
        case Label.RemoveComponent: return "Komponente entfernen";
        case Label.DuplicateComponent: return "Komponente duplizieren";
        case Label.MoveComponentUp: return "Komponente nach oben";
        case Label.MoveComponentDown: return "Komponente nach unten";
        case Label.ComponentTitle: return "Titel";
        case Label.ComponentTitleDescription: return "Zeigt Spielname und Kategorie sowie optional Icon, Versuche und abgeschlossene Runs.";
        case Label.ComponentGraph: return "Graph";
        case Label.ComponentGraphDescription: return "Visualisiert den Vorsprung/Rückstand über den ganzen Run.";
        case Label.ComponentSplitsDescription: return "Hauptkomponente für Splits mit Icon, Name, Delta und Zeit; scrollbar.";
        case Label.ComponentDetailedTimer: return "Detaillierter Timer";
        case Label.ComponentDetailedTimerDescription: return "Zeigt Gesamt‑ und Segmentzeit sowie optionale Infos.";
        case Label.ComponentTimer: return "Timer";
        case Label.ComponentTimerDescription: return "Zeigt Gesamtzeit als digitale Uhr, Farbe je Vergleich.";
        case Label.ComponentCurrentComparison: return "Aktueller Vergleich";
        case Label.ComponentCurrentComparisonDescription: return "Zeigt den Namen des aktuellen Vergleichs.";
        case Label.ComponentCurrentPace: return "Aktuelles Tempo";
        case Label.ComponentCurrentPaceDescription: return "Prognostiziert die Endzeit basierend auf dem Vergleich.";
        case Label.ComponentDelta: return "Delta";
        case Label.ComponentDeltaDescription: return "Zeigt Vorsprung/Rückstand zum Vergleich.";
        case Label.ComponentPbChance: return "PB‑Chance";
        case Label.ComponentPbChanceDescription: return "Zeigt die Wahrscheinlichkeit für ein PB, dynamisch während des Runs.";
        case Label.ComponentPossibleTimeSave: return "Mögliche Zeitersparnis";
        case Label.ComponentPossibleTimeSaveDescription: return "Zeigt die mögliche Ersparnis im Segment und insgesamt.";
        case Label.ComponentPreviousSegment: return "Vorheriges Segment";
        case Label.ComponentPreviousSegmentDescription: return "Zeigt Gewinn/Verlust im vorherigen Segment und mögliche Ersparnis.";
        case Label.ComponentSegmentTime: return "Segmentzeit";
        case Label.ComponentSegmentTimeDescription: return "Zeigt die Segmentzeit für den gewählten Vergleich.";
        case Label.ComponentSumOfBest: return "Summe der Besten";
        case Label.ComponentSumOfBestDescription: return "Zeigt die schnellstmögliche Zeit basierend auf der Historie.";
        case Label.ComponentText: return "Text";
        case Label.ComponentTextDescription: return "Zeigt Text zentriert oder links/rechts, oder eine benutzerdefinierte Variable.";
        case Label.ComponentTotalPlaytime: return "Gesamtspielzeit";
        case Label.ComponentTotalPlaytimeDescription: return "Zeigt die gesamte Spielzeit der Kategorie.";
        case Label.ComponentVariableDescription: return "Erstellt eine Textkomponente, die den Wert der Variable „{name}“ zeigt.";
        case Label.ComponentBlankSpace: return "Leerraum";
        case Label.ComponentBlankSpaceDescription: return "Leere Komponente als Abstand zwischen anderen.";
        case Label.ComponentSeparator: return "Trenner";
        case Label.ComponentSeparatorDescription: return "Zeichnet einen Trenner zwischen Komponenten.";
        case Label.AccuracySeconds: return "Sekunden";
        case Label.AccuracyTenths: return "Zehntel";
        case Label.AccuracyHundredths: return "Hundertstel";
        case Label.AccuracyMilliseconds: return "Millisekunden";
        case Label.FontStyle: return "Stil";
        case Label.FontWeight: return "Gewicht";
        case Label.FontStretch: return "Streckung";
        case Label.FontStyleNormal: return "Normal";
        case Label.FontStyleItalic: return "Kursiv";
        case Label.AlignmentAutomatic: return "Automatisch";
        case Label.AlignmentLeft: return "Links";
        case Label.AlignmentCenter: return "Zentriert";
        case Label.GradientTransparent: return "Transparent";
        case Label.GradientPlain: return "Einfarbig";
        case Label.GradientVertical: return "Vertikal";
        case Label.GradientHorizontal: return "Horizontal";
        case Label.GradientAlternating: return "Abwechselnd";
        case Label.GradientPlainDelta: return "Einfarbiges Delta";
        case Label.GradientVerticalDelta: return "Vertikales Delta";
        case Label.GradientHorizontalDelta: return "Horizontales Delta";
        case Label.LayoutBackgroundImage: return "Bild";
        case Label.LayoutBackgroundBrightness: return "Helligkeit";
        case Label.LayoutBackgroundOpacity: return "Deckkraft";
        case Label.LayoutBackgroundBlur: return "Weichzeichnung";
        case Label.LayoutDirectionVertical: return "Vertikal";
        case Label.LayoutDirectionHorizontal: return "Horizontal";
        case Label.ColumnKindTime: return "Zeit";
        case Label.ColumnKindVariable: return "Variable";
        case Label.ColumnStartWithEmpty: return "Leer";
        case Label.ColumnStartWithComparisonTime: return "Vergleichszeit";
        case Label.ColumnStartWithComparisonSegmentTime: return "Vergleichs‑Segmentzeit";
        case Label.ColumnStartWithPossibleTimeSave: return "Mögliche Zeitersparnis";
        case Label.ColumnUpdateWithDontUpdate: return "Nicht aktualisieren";
        case Label.ColumnUpdateWithSplitTime: return "Splitzeit";
        case Label.ColumnUpdateWithDelta: return "Zeit voraus / zurück";
        case Label.ColumnUpdateWithDeltaWithFallback: return "Zeit voraus / zurück oder Splitzeit, falls leer";
        case Label.ColumnUpdateWithSegmentTime: return "Segmentzeit";
        case Label.ColumnUpdateWithSegmentDelta: return "Zeit gewonnen / verloren";
        case Label.ColumnUpdateWithSegmentDeltaWithFallback: return "Zeit gewonnen / verloren oder Segmentzeit, falls leer";
        case Label.ColumnUpdateTriggerOnStartingSegment: return "Beim Start des Segments";
        case Label.ColumnUpdateTriggerContextual: return "Kontextabhängig";
        case Label.ColumnUpdateTriggerOnEndingSegment: return "Beim Ende des Segments";
        case Label.ComparisonCurrentComparison: return "Aktueller Vergleich";
        case Label.CustomVariableNoneAvailable: return "Keine Variablen verfügbar";
        case Label.CustomVariableNoneAvailableTooltip: return "Benutzerdefinierte Variablen können im Tab Variablen beim Bearbeiten der Splits definiert werden. Zusätzliche benutzerdefinierte Variablen können automatisch durch Auto‑Splitter bereitgestellt werden.";
        case Label.HotkeyButtonTooltip: return "Klicken, um eine Hotkey‑Taste aufzunehmen. Du kannst auch Gamepad‑Tasten verwenden. Globale Hotkeys sind derzeit nicht möglich. Gamepad‑Tasten funktionieren global.";
        case Label.ServerConnect: return "Verbinden";
        case Label.ServerDisconnect: return "Trennen";
        case Label.ServerConnecting: return "Verbinde...";
        case Label.ServerDisconnecting: return "Trenne...";
        case Label.ConnectToServerTitle: return "Mit Server verbinden";
        case Label.ConnectToServerDescription: return "WebSocket‑URL angeben:";
        case Label.Connect: return "Verbinden";
        case Label.UpdateAvailable: return "Eine neue Version von LiveSplit One ist verfügbar! Klicke hier, um neu zu laden.";
        case Label.UnsavedChangesBeforeUnload: return "Es gibt ungespeicherte Änderungen. Möchtest du LiveSplit One wirklich schließen?";
        case Label.OpenSidebarAriaLabel: return "Seitenleiste öffnen";
        case Label.FailedToSaveLayout: return "Layout konnte nicht gespeichert werden.";
        case Label.FailedToSaveHotkeys: return "Hotkey-Einstellungen konnten nicht gespeichert werden.";
        case Label.FailedToSaveGeneralSettings: return "Allgemeine Einstellungen konnten nicht gespeichert werden.";
        case Label.FailedToSaveSplits: return "Splits konnten nicht gespeichert werden.";
        case Label.LayoutCouldNotBeLoaded: return "Das Layout konnte nicht geladen werden. Dies ist möglicherweise kein gültiges LiveSplit- oder LiveSplit-One-Layout.";
        case Label.EmptySplitsNotSupported: return "Leere Splits werden nicht unterstützt.";
        case Label.BugEncountered: return "Ein Fehler ist aufgetreten:";
        case Label.PleaseReportIssueStart: return "Bitte melde dieses Problem ";
        case Label.ReportHere: return "hier";
        case Label.PleaseReportIssueEnd: return ".";
        case Label.BugReportInstructions: return "Um uns zu helfen, dieses Problem zu beheben, füge bitte Schritte zur Reproduktion hinzu und hänge die Splits und das Layout an, die du verwendet hast, als das Problem auftrat.";
        case Label.LoadFailedPrivateBrowsing: return "LiveSplit One konnte nicht geladen werden.\nDu bist möglicherweise im privaten Modus.\nLiveSplit One kann aufgrund der Einschränkungen des privaten Modus keine Splits, Layouts oder andere Einstellungen speichern.\nDiese Einschränkungen könnten in Zukunft aufgehoben werden.\nUm LiveSplit One vorerst zu nutzen, deaktiviere den privaten Modus in den Einstellungen.";
        case Label.LoadFailedOutdatedBrowser: return "LiveSplit One konnte nicht geladen werden.\nDu verwendest möglicherweise einen veralteten Browser.\nBitte aktualisiere deinen Browser oder deine iOS‑Version und versuche es erneut.\nEine andere Ursache könnte eine Browser‑Erweiterung sein, z. B. ein Werbeblocker, der den Zugriff auf wichtige Skripte blockiert.";
    }
}
