import { Label } from ".";

export function resolveItalian(text: Label): string {
    switch (text) {
        case Label.Ok: return "OK";
        case Label.Cancel: return "Annulla";
        case Label.Settings: return "Impostazioni";
        case Label.Language: return "Lingua";
        case Label.LanguageDescription: return "Imposta la lingua utilizzata nell'applicazione.";
        case Label.LanguageAuto: return "Automatico";
        case Label.Theme: return "Tema";
        case Label.ThemeDescription: return "Determina se seguire il tema di sistema o forzare una modalità chiara o scura.";
        case Label.ThemeLightMode: return "Modalità chiara";
        case Label.ThemeDarkMode: return "Modalità scura";
        case Label.HotkeysHeading: return "Scorciatoie";
        case Label.GeneralHeading: return "Generale";
        case Label.NetworkHeading: return "Rete";
        case Label.FrameRate: return "Frequenza dei fotogrammi";
        case Label.FrameRateDescription: return "Determina la frequenza dei fotogrammi con cui visualizzare il timer. «Consapevole della batteria» prova a determinare il tipo di dispositivo e lo stato di carica per scegliere una buona frequenza. «Abbina allo schermo» fa corrispondere il timer alla frequenza di aggiornamento dello schermo.";
        case Label.FrameRateBatteryAware: return "Consapevole della batteria";
        case Label.FrameRateMatchScreen: return "Abbina allo schermo";
        case Label.SaveOnReset: return "Salva al reset";
        case Label.SaveOnResetDescription: return "Determina se salvare automaticamente gli split quando si resetta il timer.";
        case Label.ShowControlButtons: return "Mostra pulsanti di controllo";
        case Label.ShowControlButtonsDescription: return "Determina se mostrare pulsanti sotto il timer che consentono di controllarlo. Quando disattivati, devi usare le scorciatoie.";
        case Label.ShowManualGameTimeInput: return "Mostra input manuale del tempo di gioco";
        case Label.ShowManualGameTimeInputDescription: return "Mostra una casella di testo sotto il timer che permette di inserire manualmente il tempo di gioco. Avvii il timer e fai gli split premendo Invio nella casella di testo. Assicurati di confrontare con «Game Time».";
        case Label.ManualGameTimeMode: return "Modalità tempo di gioco manuale";
        case Label.ManualGameTimeModeDescription: return "Determina se inserire il tempo di gioco manuale come tempi segmento o tempi split.";
        case Label.ManualGameTimeModeSegmentTimes: return "Tempi segmento";
        case Label.ManualGameTimeModeSplitTimes: return "Tempi split";
        case Label.AlwaysOnTop: return "Sempre in primo piano";
        case Label.AlwaysOnTopDescription: return "Mantiene la finestra sempre sopra le altre finestre.";
        case Label.SpeedrunComIntegration: return "Integrazione Speedrun.com";
        case Label.SpeedrunComIntegrationDescription: return "Richiede l'elenco dei giochi, delle categorie e delle classifiche da speedrun.com.";
        case Label.ServerConnection: return "Connessione server";
        case Label.ServerConnectionDescription: return "Consente di connettersi a un server WebSocket che può controllare il timer inviando vari comandi. I comandi sono attualmente un sottoinsieme di quelli supportati dal LiveSplit originale.";
        case Label.ServerConnectionExperimental: return "Questa funzionalità è sperimentale e il protocollo probabilmente cambierà in futuro.";
        case Label.HotkeyAlreadyInUse: return "La scorciatoia è già in uso.";
        case Label.Start: return "Avvia";
        case Label.Resume: return "Riprendi";
        case Label.Pause: return "Pausa";
        case Label.UndoSplit: return "Annulla split";
        case Label.Reset: return "Reimposta";
        case Label.SkipSplit: return "Salta split";
        case Label.ManualGameTimePlaceholder: return "Tempo di gioco manuale";
        case Label.LiveSplitLogoAlt: return "Logo LiveSplit";
        case Label.LiveSplitOne: return "LiveSplit One";
        case Label.Splits: return "Splits";
        case Label.Layout: return "Layout";
        case Label.CompareAgainst: return "Confronta con";
        case Label.RealTime: return "Tempo reale";
        case Label.GameTime: return "Tempo di gioco";
        case Label.PopOut: return "Finestra separata";
        case Label.About: return "Informazioni";
        case Label.Back: return "Indietro";
        case Label.AboutVersionPrefix: return "Versione:";
        case Label.AboutDescription: return "LiveSplit One è una versione multipiattaforma di LiveSplit, il timer elegante e altamente personalizzabile per speedrunner.";
        case Label.AboutViewSource: return "Visualizza il codice sorgente su GitHub";
        case Label.AboutRecentChanges: return "Modifiche recenti";
        case Label.AboutContributors: return "Collaboratori";
        case Label.Loading: return "Caricamento...";
        case Label.Add: return "Aggiungi";
        case Label.Import: return "Importa";
        case Label.OpenSplits: return "Apri split";
        case Label.EditSplits: return "Modifica split";
        case Label.ExportSplits: return "Esporta split";
        case Label.CopySplits: return "Copia split";
        case Label.RemoveSplits: return "Rimuovi split";
        case Label.Untitled: return "Senza titolo";
        case Label.NoCategory: return "—";
        case Label.DiscardChangesTitle: return "Scartare le modifiche?";
        case Label.DiscardChangesDescription: return "Gli split attuali sono stati modificati e hanno modifiche non salvate. Vuoi continuare e scartare le modifiche?";
        case Label.DeleteSplitsTitle: return "Eliminare gli split?";
        case Label.DeleteSplitsDescription: return "Sei sicuro di voler eliminare gli split? Questa operazione non può essere annullata.";
        case Label.SaveBestTimesTitle: return "Salvare i migliori tempi?";
        case Label.SaveBestTimesDescription: return "Hai migliorato alcuni dei tuoi migliori tempi. Vuoi aggiornarli?";
        case Label.Yes: return "Sì";
        case Label.No: return "No";
        case Label.DontReset: return "Non azzerare";
        case Label.FailedToExportSplits: return "Impossibile esportare gli split.";
        case Label.CantImportEmptySplits: return "Non è possibile importare split vuoti.";
        case Label.FailedToReadFile: return "Impossibile leggere il file:";
        case Label.FailedToImportSplits: return "Impossibile importare gli split:";
        case Label.CouldNotParseSplits: return "Impossibile analizzare gli split.";
        case Label.LoadedSplitsInvalid: return "Gli split caricati non sono validi.";
        case Label.NewSegmentName: return "Tempo";
        case Label.EditWhileRunningError: return "Non puoi modificare gli split mentre il timer è in esecuzione.";
        case Label.Edit: return "Modifica";
        case Label.Save: return "Salva";
        case Label.Export: return "Esporta";
        case Label.FailedToParseTimeSpan: return "Impossibile analizzare TimeSpan";
        case Label.Default: return "Predefinito";
        case Label.Game: return "Gioco";
        case Label.Category: return "Categoria";
        case Label.StartTimerAt: return "Avvia timer a";
        case Label.Attempts: return "Tentativi";
        case Label.SplitsEditor: return "Editor degli split";
        case Label.Variables: return "Variabili";
        case Label.Rules: return "Regole";
        case Label.Leaderboard: return "Classifica";
        case Label.InsertAbove: return "Inserisci sopra";
        case Label.InsertBelow: return "Inserisci sotto";
        case Label.RemoveSegment: return "Rimuovi segmento";
        case Label.MoveUp: return "Sposta su";
        case Label.MoveDown: return "Sposta giù";
        case Label.AddVariable: return "Aggiungi variabile";
        case Label.OpenPbPage: return "Apri pagina PB";
        case Label.AssociateRun: return "Associa run";
        case Label.Icon: return "Icona";
        case Label.SegmentName: return "Nome segmento";
        case Label.SplitTime: return "Tempo split";
        case Label.SegmentTime: return "Tempo segmento";
        case Label.BestSegment: return "Miglior segmento";
        case Label.SpeedrunComVariableTooltip: return "Variabile di speedrun.com specifica del gioco.";
        case Label.Region: return "Regione";
        case Label.RegionDescription: return "La regione del gioco che si sta giocando.";
        case Label.Platform: return "Piattaforma";
        case Label.PlatformDescription: return "La piattaforma su cui si gioca.";
        case Label.UsesEmulator: return "Usa emulatore";
        case Label.UsesEmulatorDescription: return "Se viene usato un emulatore.";
        case Label.CustomVariableTooltip: return "Variabile personalizzata da te. Può essere mostrata con il componente testo.";
        case Label.NoVariables: return "Al momento non ci sono variabili personalizzate per questo gioco.";
        case Label.NoVariablesWithSpeedrunCom: return "Al momento non ci sono variabili di speedrun.com o personalizzate per questo gioco.";
        case Label.TimedWithoutLoads: return "sono cronometrate senza tempi di caricamento";
        case Label.TimedWithGameTime: return "sono cronometrate con Game Time";
        case Label.RequireVideoProof: return "richiedono prova video";
        case Label.RunsOfThisGamePrefix: return "Le run di questo gioco ";
        case Label.RunsOfThisGameSuffix: return ".";
        case Label.And: return "e";
        case Label.SetIcon: return "Imposta icona";
        case Label.SetIconDescription: return "Scegli un'immagine come icona del gioco. Alcuni formati potrebbero non funzionare ovunque.";
        case Label.DownloadBoxArt: return "Scarica copertina";
        case Label.DownloadBoxArtDescription: return "Tenta di scaricare la copertina da speedrun.com per impostarla come icona del gioco.";
        case Label.DownloadIcon: return "Scarica icona";
        case Label.DownloadIconDescription: return "Tenta di scaricare l'icona del gioco da speedrun.com.";
        case Label.RemoveIcon: return "Rimuovi icona";
        case Label.RemoveIconDescription: return "Rimuove l'icona del gioco.";
        case Label.CleaningMenu: return "Pulizia…";
        case Label.ClearOnlyHistory: return "Cancella solo cronologia";
        case Label.ClearOnlyHistoryDescription: return "Gli split salvano tutta la cronologia delle run. Questa azione cancella la cronologia senza influire su PB, migliori segmenti o confronti.";
        case Label.ClearAllTimes: return "Cancella tutti i tempi";
        case Label.ClearAllTimesDescription: return "Rimuove tutti i tempi e la cronologia, rendendo gli split vuoti.";
        case Label.CleanSumOfBest: return "Pulisci la somma dei migliori";
        case Label.CleanSumOfBestDescription: return "Permette di rimuovere interattivamente problemi nella cronologia dei segmenti che rendono la somma dei migliori segmenti imprecisa.";
        case Label.ComparisonsMenu: return "Confronti…";
        case Label.AddComparison: return "Aggiungi confronto";
        case Label.AddComparisonDescription: return "Aggiunge un confronto personalizzato dove puoi salvare i tempi.";
        case Label.ImportComparison: return "Importa confronto";
        case Label.ImportComparisonDescription: return "Importa il Personal Best di un file splits come confronto.";
        case Label.GenerateGoalComparison: return "Genera confronto obiettivo";
        case Label.GenerateGoalComparisonDescription: return "Genera un confronto obiettivo basato su un tempo obiettivo.";
        case Label.CopyComparison: return "Copia confronto";
        case Label.CopyComparisonDescription: return "Copia un confronto esistente come nuovo confronto personalizzato.";
        case Label.SetSegmentIcon: return "Imposta icona";
        case Label.SetSegmentIconDescription: return "Scegli un'immagine come icona del segmento. Alcuni formati potrebbero non funzionare ovunque.";
        case Label.RemoveSegmentIcon: return "Rimuovi icona";
        case Label.RemoveSegmentIconDescription: return "Rimuove l'icona del segmento.";
        case Label.Rename: return "Rinomina";
        case Label.RenameDescription: return "Scegli un nuovo nome per il confronto personalizzato. Nomi riservati o duplicati non sono consentiti.";
        case Label.CopyAction: return "Copia";
        case Label.CopyDescription: return "Crea una copia del confronto personalizzato.";
        case Label.ACopy: return "Copia";
        case Label.Remove: return "Rimuovi";
        case Label.RemoveDescription: return "Rimuove il confronto personalizzato.";
        case Label.AnyPercent: return "Any%";
        case Label.LowPercent: return "Low%";
        case Label.HundredPercent: return "100%";
        case Label.AddComparisonPrompt: return "Specifica il nome del confronto da aggiungere:";
        case Label.ComparisonAddError: return "Impossibile aggiungere il confronto. Potrebbe essere duplicato o riservato.";
        case Label.ImportComparisonPrompt: return "Specifica il nome del confronto da importare:";
        case Label.GenerateGoalComparisonPrompt: return "Specifica il tempo che vuoi raggiungere:";
        case Label.Generate: return "Genera";
        case Label.GenerateGoalComparisonError: return "Impossibile generare il confronto obiettivo. Specifica un tempo valido.";
        case Label.CopyComparisonPrompt: return "Specifica il nome del confronto da copiare:";
        case Label.CopyComparisonError: return "Impossibile copiare il confronto. Il confronto potrebbe non esistere.";
        case Label.NothingToCleanUp: return "Non c'è nulla da pulire.";
        case Label.CleanPrompt: return "Pulire?";
        case Label.AssociateRunPrompt: return "Specifica l'ID o l'URL speedrun.com della run:";
        case Label.Associate: return "Associa";
        case Label.InvalidSpeedrunUrl: return "ID o URL speedrun.com non valido.";
        case Label.AssociateRunError: return "Impossibile associare la run. L'ID potrebbe non essere valido.";
        case Label.AddVariablePrompt: return "Specifica il nome della variabile personalizzata da aggiungere:";
        case Label.RenameComparison: return "Rinomina confronto";
        case Label.RenameComparisonPrompt: return "Specifica il nuovo nome del confronto:";
        case Label.ComparisonRenameError: return "Impossibile rinominare il confronto. Potrebbe essere duplicato o riservato.";
        case Label.GameNotFound: return "Gioco non trovato.";
        case Label.NoBoxArt: return "Il gioco non ha una copertina.";
        case Label.DownloadBoxArtError: return "Impossibile scaricare la copertina.";
        case Label.NoGameIcon: return "Il gioco non ha un'icona.";
        case Label.DownloadIconError: return "Impossibile scaricare l'icona.";
        case Label.Rank: return "Posizione";
        case Label.Player: return "Giocatore";
        case Label.Time: return "Tempo";
        case Label.Date: return "Data:";
        case Label.Emulator: return "Emulatore";
        case Label.EmulatorTag: return "Emulatore";
        case Label.ObsoleteRuns: return "Run obsolete";
        case Label.Shown: return "Mostrate";
        case Label.Hidden: return "Nascoste";
        case Label.OpenLeaderboard: return "Apri classifica";
        case Label.Filters: return "Filtri";
        case Label.LayoutEditor: return "Editor layout";
        case Label.Component: return "Componente";
        case Label.AddComponent: return "Aggiungi componente";
        case Label.RemoveComponent: return "Rimuovi componente";
        case Label.DuplicateComponent: return "Duplica componente";
        case Label.MoveComponentUp: return "Sposta componente su";
        case Label.MoveComponentDown: return "Sposta componente giù";
        case Label.ComponentTitle: return "Titolo";
        case Label.ComponentTitleDescription: return "Mostra nome gioco e categoria, oltre a icona, tentativi e run completate.";
        case Label.ComponentGraph: return "Grafico";
        case Label.ComponentGraphDescription: return "Visualizza vantaggio/svantaggio della run rispetto al confronto.";
        case Label.ComponentSplitsDescription: return "Componente principale per gli split con icona, nome, delta e tempo; scorrevole.";
        case Label.ComponentDetailedTimer: return "Timer dettagliato";
        case Label.ComponentDetailedTimerDescription: return "Mostra tempo totale e del segmento, più info opzionali.";
        case Label.ComponentTimer: return "Timer";
        case Label.ComponentTimerDescription: return "Mostra il tempo totale come orologio digitale; colore in base al confronto.";
        case Label.ComponentCurrentComparison: return "Confronto attuale";
        case Label.ComponentCurrentComparisonDescription: return "Mostra il nome del confronto attuale.";
        case Label.ComponentCurrentPace: return "Pace attuale";
        case Label.ComponentCurrentPaceDescription: return "Predice il tempo finale in base al confronto scelto.";
        case Label.ComponentDelta: return "Delta";
        case Label.ComponentDeltaDescription: return "Mostra quanto sei avanti o indietro rispetto al confronto.";
        case Label.ComponentPbChance: return "Probabilità PB";
        case Label.ComponentPbChanceDescription: return "Mostra la probabilità di battere il PB, dinamica durante la run.";
        case Label.ComponentPossibleTimeSave: return "Tempo risparmiabile";
        case Label.ComponentPossibleTimeSaveDescription: return "Mostra il tempo risparmiabile nel segmento e totale.";
        case Label.ComponentPreviousSegment: return "Segmento precedente";
        case Label.ComponentPreviousSegmentDescription: return "Mostra tempo guadagnato/perso nel segmento precedente e risparmio potenziale.";
        case Label.ComponentSegmentTime: return "Tempo segmento";
        case Label.ComponentSegmentTimeDescription: return "Mostra il tempo del segmento per il confronto scelto.";
        case Label.ComponentSumOfBest: return "Somma dei migliori";
        case Label.ComponentSumOfBestDescription: return "Mostra il tempo più veloce possibile basato sulla storia.";
        case Label.ComponentText: return "Testo";
        case Label.ComponentTextDescription: return "Mostra testo centrato o sinistra/destra, oppure una variabile personalizzata.";
        case Label.ComponentTotalPlaytime: return "Tempo di gioco totale";
        case Label.ComponentTotalPlaytimeDescription: return "Mostra il tempo totale di gioco della categoria.";
        case Label.ComponentVariableDescription: return "Crea un componente testo che mostra il valore della variabile «{name}».";
        case Label.ComponentBlankSpace: return "Spazio vuoto";
        case Label.ComponentBlankSpaceDescription: return "Componente vuoto usato come spaziatura.";
        case Label.ComponentSeparator: return "Separatore";
        case Label.ComponentSeparatorDescription: return "Rende un separatore tra componenti.";
        case Label.AccuracySeconds: return "Secondi";
        case Label.AccuracyTenths: return "Decimi";
        case Label.AccuracyHundredths: return "Centesimi";
        case Label.AccuracyMilliseconds: return "Millisecondi";
        case Label.FontStyle: return "Stile";
        case Label.FontWeight: return "Peso";
        case Label.FontStretch: return "Allungamento";
        case Label.FontStyleNormal: return "Normale";
        case Label.FontStyleItalic: return "Corsivo";
        case Label.AlignmentAutomatic: return "Automatico";
        case Label.AlignmentLeft: return "Sinistra";
        case Label.AlignmentCenter: return "Centro";
        case Label.GradientTransparent: return "Trasparente";
        case Label.GradientPlain: return "Tinta unita";
        case Label.GradientVertical: return "Verticale";
        case Label.GradientHorizontal: return "Orizzontale";
        case Label.GradientAlternating: return "Alternato";
        case Label.GradientPlainDelta: return "Delta tinta unita";
        case Label.GradientVerticalDelta: return "Delta verticale";
        case Label.GradientHorizontalDelta: return "Delta orizzontale";
        case Label.LayoutBackgroundImage: return "Immagine";
        case Label.LayoutBackgroundBrightness: return "Luminosità";
        case Label.LayoutBackgroundOpacity: return "Opacità";
        case Label.LayoutBackgroundBlur: return "Sfocatura";
        case Label.LayoutDirectionVertical: return "Verticale";
        case Label.LayoutDirectionHorizontal: return "Orizzontale";
        case Label.ColumnKindTime: return "Tempo";
        case Label.ColumnKindVariable: return "Variabile";
        case Label.ColumnStartWithEmpty: return "Vuoto";
        case Label.ColumnStartWithComparisonTime: return "Tempo di confronto";
        case Label.ColumnStartWithComparisonSegmentTime: return "Tempo segmento di confronto";
        case Label.ColumnStartWithPossibleTimeSave: return "Tempo risparmiabile";
        case Label.ColumnUpdateWithDontUpdate: return "Non aggiornare";
        case Label.ColumnUpdateWithSplitTime: return "Tempo split";
        case Label.ColumnUpdateWithDelta: return "Tempo avanti / indietro";
        case Label.ColumnUpdateWithDeltaWithFallback: return "Tempo avanti / indietro o tempo split se vuoto";
        case Label.ColumnUpdateWithSegmentTime: return "Tempo segmento";
        case Label.ColumnUpdateWithSegmentDelta: return "Tempo guadagnato / perso";
        case Label.ColumnUpdateWithSegmentDeltaWithFallback: return "Tempo guadagnato / perso o tempo segmento se vuoto";
        case Label.ColumnUpdateTriggerOnStartingSegment: return "All’inizio del segmento";
        case Label.ColumnUpdateTriggerContextual: return "Contestuale";
        case Label.ColumnUpdateTriggerOnEndingSegment: return "Alla fine del segmento";
        case Label.ComparisonCurrentComparison: return "Confronto attuale";
        case Label.CustomVariableNoneAvailable: return "Nessuna variabile disponibile";
        case Label.CustomVariableNoneAvailableTooltip: return "Le variabili personalizzate possono essere definite nella scheda Variabili durante la modifica degli split. Ulteriori variabili personalizzate possono essere fornite automaticamente dagli auto splitter.";
        case Label.HotkeyButtonTooltip: return "Fai clic per registrare un tasto di scelta rapida. Puoi usare anche i pulsanti del gamepad. Gli hotkey globali al momento non sono possibili. I pulsanti del gamepad funzionano globalmente.";
        case Label.ServerConnect: return "Connetti";
        case Label.ServerDisconnect: return "Disconnetti";
        case Label.ServerConnecting: return "Connessione...";
        case Label.ServerDisconnecting: return "Disconnessione...";
        case Label.ConnectToServerTitle: return "Connetti al server";
        case Label.ConnectToServerDescription: return "Specifica l’URL WebSocket:";
        case Label.Connect: return "Connetti";
        case Label.UpdateAvailable: return "È disponibile una nuova versione di LiveSplit One! Clicca qui per ricaricare.";
        case Label.UnsavedChangesBeforeUnload: return "Ci sono modifiche non salvate. Vuoi davvero chiudere LiveSplit One?";
        case Label.OpenSidebarAriaLabel: return "Apri barra laterale";
        case Label.FailedToSaveLayout: return "Impossibile salvare il layout.";
        case Label.FailedToSaveHotkeys: return "Impossibile salvare le impostazioni dei tasti di scelta rapida.";
        case Label.FailedToSaveGeneralSettings: return "Impossibile salvare le impostazioni generali.";
        case Label.FailedToSaveSplits: return "Impossibile salvare gli split.";
        case Label.LayoutCouldNotBeLoaded: return "Il layout non può essere caricato. Potrebbe non essere un layout LiveSplit o LiveSplit One valido.";
        case Label.EmptySplitsNotSupported: return "Gli split vuoti non sono supportati.";
        case Label.BugEncountered: return "Hai riscontrato un bug:";
        case Label.PleaseReportIssueStart: return "Segnala questo problema ";
        case Label.ReportHere: return "qui";
        case Label.PleaseReportIssueEnd: return ".";
        case Label.BugReportInstructions: return "Per aiutarci a risolvere questo problema, includi i passaggi per riprodurlo e allega gli split e il layout che stavi usando quando si è verificato il problema.";
        case Label.LoadFailedPrivateBrowsing: return "Impossibile caricare LiveSplit One.\nPotresti essere in modalità di navigazione privata.\nLiveSplit One non può salvare split, layout o altre impostazioni a causa delle limitazioni della modalità privata del browser.\nQueste limitazioni potrebbero essere rimosse in futuro.\nPer usare LiveSplit One ora, disattiva la navigazione privata nelle impostazioni.";
        case Label.LoadFailedOutdatedBrowser: return "Impossibile caricare LiveSplit One.\nPotresti usare un browser non aggiornato.\nAggiorna il browser o la versione di iOS e riprova.\nUn altro motivo potrebbe essere un’estensione del browser, ad esempio un adblocker, che blocca l’accesso a script importanti.";
    }
}
