import { Label } from ".";

export function resolveJapanese(text: Label): string {
    switch (text) {
        case Label.Ok: return "OK";
        case Label.Cancel: return "キャンセル";
        case Label.Settings: return "設定";
        case Label.Language: return "言語";
        case Label.LanguageDescription: return "アプリケーションで使用される言語を設定します。";
        case Label.LanguageAuto: return "自動";
        case Label.HotkeysHeading: return "ホットキー";
        case Label.GeneralHeading: return "一般";
        case Label.NetworkHeading: return "ネットワーク";
        case Label.FrameRate: return "フレームレート";
        case Label.FrameRateDescription: return "タイマーを表示するフレームレートを決定します。「バッテリー考慮」はデバイスの種類と充電状態を判断して適切なフレームレートを選択します。「画面に合わせる」はタイマーを画面のリフレッシュレートに合わせます。";
        case Label.FrameRateBatteryAware: return "バッテリー考慮";
        case Label.FrameRateMatchScreen: return "画面に合わせる";
        case Label.SaveOnReset: return "リセット時に保存";
        case Label.SaveOnResetDescription: return "タイマーをリセットしたときにスプリットを自動的に保存するかどうかを決定します。";
        case Label.ShowControlButtons: return "コントロールボタンを表示";
        case Label.ShowControlButtonsDescription: return "タイマー下に制御用のボタンを表示するかどうかを決定します。無効にした場合はホットキーを使用する必要があります。";
        case Label.ShowManualGameTimeInput: return "手動のゲームタイム入力を表示";
        case Label.ShowManualGameTimeInputDescription: return "タイマー下にゲームタイムを手動で入力できるテキストボックスを表示します。テキストボックスで Enter キーを押すとタイマーを開始し、スプリットします。「Game Time」との比較を忘れないでください。";
        case Label.ManualGameTimeMode: return "手動ゲームタイムモード";
        case Label.ManualGameTimeModeDescription: return "手動のゲームタイムをセグメントタイムとして入力するか、スプリットタイムとして入力するかを決定します。";
        case Label.ManualGameTimeModeSegmentTimes: return "セグメントタイム";
        case Label.ManualGameTimeModeSplitTimes: return "スプリットタイム";
        case Label.AlwaysOnTop: return "常に最前面";
        case Label.AlwaysOnTopDescription: return "ウィンドウを常に他のウィンドウの前面に表示します。";
        case Label.SpeedrunComIntegration: return "Speedrun.com 連携";
        case Label.SpeedrunComIntegrationDescription: return "speedrun.com からゲーム、カテゴリ、リーダーボードの一覧を取得します。";
        case Label.ServerConnection: return "サーバー接続";
        case Label.ServerConnectionDescription: return "WebSocket サーバーに接続して、さまざまなコマンドを送信することでタイマーを制御できます。これらのコマンドは現在、元の LiveSplit がサポートするコマンドの一部です。";
        case Label.ServerConnectionExperimental: return "この機能は実験的で、プロトコルは将来変更される可能性があります。";
        case Label.HotkeyAlreadyInUse: return "このホットキーは既に使用されています。";
        case Label.Start: return "開始";
        case Label.Resume: return "再開";
        case Label.Pause: return "一時停止";
        case Label.UndoSplit: return "スプリットを戻す";
        case Label.Reset: return "リセット";
        case Label.SkipSplit: return "スプリットをスキップ";
        case Label.ManualGameTimePlaceholder: return "手動ゲームタイム";
        case Label.LiveSplitLogoAlt: return "LiveSplit ロゴ";
        case Label.LiveSplitOne: return "LiveSplit One";
        case Label.Splits: return "スプリット";
        case Label.Layout: return "レイアウト";
        case Label.CompareAgainst: return "比較対象";
        case Label.RealTime: return "リアルタイム";
        case Label.GameTime: return "ゲームタイム";
        case Label.PopOut: return "ポップアウト";
        case Label.About: return "このアプリについて";
        case Label.Back: return "戻る";
        case Label.AboutVersionPrefix: return "バージョン：";
        case Label.AboutDescription: return "LiveSplit One は LiveSplit のマルチプラットフォーム版で、スピードランナー向けの洗練された高いカスタマイズ性を持つタイマーです。";
        case Label.AboutViewSource: return "GitHub でソースコードを見る";
        case Label.AboutRecentChanges: return "最近の変更";
        case Label.AboutContributors: return "貢献者";
        case Label.Loading: return "読み込み中...";
        case Label.Add: return "追加";
        case Label.Import: return "インポート";
        case Label.OpenSplits: return "スプリットを開く";
        case Label.EditSplits: return "スプリットを編集";
        case Label.ExportSplits: return "スプリットをエクスポート";
        case Label.CopySplits: return "スプリットをコピー";
        case Label.RemoveSplits: return "スプリットを削除";
        case Label.Untitled: return "無題";
        case Label.NoCategory: return "—";
        case Label.DiscardChangesTitle: return "変更を破棄しますか？";
        case Label.DiscardChangesDescription: return "現在のスプリットには未保存の変更があります。続行して変更を破棄しますか？";
        case Label.DeleteSplitsTitle: return "スプリットを削除しますか？";
        case Label.DeleteSplitsDescription: return "スプリットを削除してもよろしいですか？この操作は元に戻せません。";
        case Label.SaveBestTimesTitle: return "ベストタイムを保存しますか？";
        case Label.SaveBestTimesDescription: return "いくつかのベストタイムを更新しました。更新しますか？";
        case Label.Yes: return "はい";
        case Label.No: return "いいえ";
        case Label.DontReset: return "リセットしない";
        case Label.FailedToExportSplits: return "スプリットのエクスポートに失敗しました。";
        case Label.CantImportEmptySplits: return "空のスプリットはインポートできません。";
        case Label.FailedToReadFile: return "ファイルの読み込みに失敗しました：";
        case Label.FailedToImportSplits: return "スプリットのインポートに失敗しました：";
        case Label.CouldNotParseSplits: return "スプリットを解析できませんでした。";
        case Label.LoadedSplitsInvalid: return "読み込んだスプリットが無効です。";
        case Label.NewSegmentName: return "時間";
        case Label.EditWhileRunningError: return "タイマーが動作中はスプリットを編集できません。";
        case Label.Edit: return "編集";
        case Label.Save: return "保存";
        case Label.Export: return "エクスポート";
        case Label.FailedToParseTimeSpan: return "TimeSpan を解析できませんでした";
        case Label.Default: return "既定";
        case Label.Game: return "ゲーム";
        case Label.Category: return "カテゴリ";
        case Label.StartTimerAt: return "開始時刻";
        case Label.Attempts: return "試行回数";
        case Label.SplitsEditor: return "スプリット編集";
        case Label.Variables: return "変数";
        case Label.Rules: return "ルール";
        case Label.Leaderboard: return "リーダーボード";
        case Label.InsertAbove: return "上に挿入";
        case Label.InsertBelow: return "下に挿入";
        case Label.RemoveSegment: return "セグメント削除";
        case Label.MoveUp: return "上へ移動";
        case Label.MoveDown: return "下へ移動";
        case Label.AddVariable: return "変数を追加";
        case Label.OpenPbPage: return "PB ページを開く";
        case Label.AssociateRun: return "ランを関連付け";
        case Label.Icon: return "アイコン";
        case Label.SegmentName: return "セグメント名";
        case Label.SplitTime: return "スプリットタイム";
        case Label.SegmentTime: return "セグメントタイム";
        case Label.BestSegment: return "ベストセグメント";
        case Label.SpeedrunComVariableTooltip: return "speedrun.com のゲーム固有の変数。";
        case Label.Region: return "地域";
        case Label.RegionDescription: return "プレイしているゲームの地域。";
        case Label.Platform: return "プラットフォーム";
        case Label.PlatformDescription: return "ゲームをプレイするプラットフォーム。";
        case Label.UsesEmulator: return "エミュレータ使用";
        case Label.UsesEmulatorDescription: return "エミュレータを使用しているかどうか。";
        case Label.CustomVariableTooltip: return "あなたが指定したカスタム変数。テキストコンポーネントで表示できます。";
        case Label.NoVariables: return "このゲームには現在カスタム変数がありません。";
        case Label.NoVariablesWithSpeedrunCom: return "このゲームには speedrun.com 変数またはカスタム変数がありません。";
        case Label.TimedWithoutLoads: return "ロード時間を除いて計測されます";
        case Label.TimedWithGameTime: return "ゲームタイムで計測されます";
        case Label.RequireVideoProof: return "動画証明が必要です";
        case Label.RunsOfThisGamePrefix: return "このゲームのランは";
        case Label.RunsOfThisGameSuffix: return "。";
        case Label.And: return "と";
        case Label.SetIcon: return "アイコン設定";
        case Label.SetIconDescription: return "画像ファイルを選択してゲームのアイコンに設定します。形式によっては対応していない場合があります。";
        case Label.DownloadBoxArt: return "ボックスアートをダウンロード";
        case Label.DownloadBoxArtDescription: return "speedrun.com からボックスアートをダウンロードしてゲームのアイコンに設定します。";
        case Label.DownloadIcon: return "アイコンをダウンロード";
        case Label.DownloadIconDescription: return "speedrun.com からゲームのアイコンをダウンロードします。";
        case Label.RemoveIcon: return "アイコン削除";
        case Label.RemoveIconDescription: return "ゲームのアイコンを削除します。";
        case Label.CleaningMenu: return "クリーンアップ…";
        case Label.ClearOnlyHistory: return "履歴のみ削除";
        case Label.ClearOnlyHistoryDescription: return "すべてのラン履歴（各セグメントタイム）を削除します。PB、ベストセグメント、比較には影響しません。";
        case Label.ClearAllTimes: return "全ての時間を削除";
        case Label.ClearAllTimesDescription: return "履歴を含むすべての時間を削除し、スプリットを初期状態に戻します。";
        case Label.CleanSumOfBest: return "ベスト合計をクリーン";
        case Label.CleanSumOfBestDescription: return "セグメント履歴の問題を対話的に修正し、ベストセグメント合計の精度を高めます。";
        case Label.ComparisonsMenu: return "比較…";
        case Label.AddComparison: return "比較を追加";
        case Label.AddComparisonDescription: return "カスタム比較を追加します。";
        case Label.ImportComparison: return "比較をインポート";
        case Label.ImportComparisonDescription: return "スプリットファイルの PB を比較としてインポートします。";
        case Label.GenerateGoalComparison: return "目標比較を生成";
        case Label.GenerateGoalComparisonDescription: return "目標タイムに基づく比較を生成します。";
        case Label.CopyComparison: return "比較をコピー";
        case Label.CopyComparisonDescription: return "既存の比較をコピーして新しい比較を作成します。";
        case Label.SetSegmentIcon: return "アイコン設定";
        case Label.SetSegmentIconDescription: return "画像ファイルを選択してセグメントのアイコンに設定します。";
        case Label.RemoveSegmentIcon: return "アイコン削除";
        case Label.RemoveSegmentIconDescription: return "セグメントのアイコンを削除します。";
        case Label.Rename: return "名前変更";
        case Label.RenameDescription: return "比較の新しい名前を選択します。予約名や重複名は使用できません。";
        case Label.CopyAction: return "コピー";
        case Label.CopyDescription: return "比較のコピーを作成します。";
        case Label.ACopy: return "コピー";
        case Label.Remove: return "削除";
        case Label.RemoveDescription: return "比較を削除します。";
        case Label.AnyPercent: return "Any%";
        case Label.LowPercent: return "Low%";
        case Label.HundredPercent: return "100%";
        case Label.AddComparisonPrompt: return "追加する比較の名前を入力してください：";
        case Label.ComparisonAddError: return "比較を追加できませんでした。重複または予約名の可能性があります。";
        case Label.ImportComparisonPrompt: return "インポートする比較の名前を入力してください：";
        case Label.GenerateGoalComparisonPrompt: return "達成したい時間を入力してください：";
        case Label.Generate: return "生成";
        case Label.GenerateGoalComparisonError: return "目標比較の生成に失敗しました。時間が正しいか確認してください。";
        case Label.CopyComparisonPrompt: return "コピーする比較の名前を入力してください：";
        case Label.CopyComparisonError: return "比較のコピーに失敗しました。比較が存在しない可能性があります。";
        case Label.NothingToCleanUp: return "クリーンアップするものはありません。";
        case Label.CleanPrompt: return "クリーンアップしますか？";
        case Label.AssociateRunPrompt: return "speedrun.com のラン ID または URL を入力してください：";
        case Label.Associate: return "関連付け";
        case Label.InvalidSpeedrunUrl: return "speedrun.com の ID または URL が無効です。";
        case Label.AssociateRunError: return "ランを関連付けできませんでした。ID が無効な可能性があります。";
        case Label.AddVariablePrompt: return "追加するカスタム変数名を入力してください：";
        case Label.RenameComparison: return "比較名を変更";
        case Label.RenameComparisonPrompt: return "新しい比較名を入力してください：";
        case Label.ComparisonRenameError: return "比較名を変更できませんでした。重複または予約名の可能性があります。";
        case Label.GameNotFound: return "ゲームが見つかりませんでした。";
        case Label.NoBoxArt: return "このゲームにはボックスアートがありません。";
        case Label.DownloadBoxArtError: return "ボックスアートをダウンロードできませんでした。";
        case Label.NoGameIcon: return "このゲームにはアイコンがありません。";
        case Label.DownloadIconError: return "アイコンをダウンロードできませんでした。";
        case Label.Rank: return "順位";
        case Label.Player: return "プレイヤー";
        case Label.Time: return "時間";
        case Label.Date: return "日付：";
        case Label.Emulator: return "エミュレータ";
        case Label.EmulatorTag: return "エミュレータ";
        case Label.ObsoleteRuns: return "古い記録";
        case Label.Shown: return "表示";
        case Label.Hidden: return "非表示";
        case Label.OpenLeaderboard: return "リーダーボードを開く";
        case Label.Filters: return "フィルター";
        case Label.LayoutEditor: return "レイアウトエディター";
        case Label.Component: return "コンポーネント";
        case Label.AddComponent: return "コンポーネント追加";
        case Label.RemoveComponent: return "コンポーネント削除";
        case Label.DuplicateComponent: return "コンポーネント複製";
        case Label.MoveComponentUp: return "コンポーネント上へ";
        case Label.MoveComponentDown: return "コンポーネント下へ";
        case Label.ComponentTitle: return "タイトル";
        case Label.ComponentTitleDescription: return "ゲーム名とカテゴリ、アイコン、試行回数、完走数を表示します。";
        case Label.ComponentGraph: return "グラフ";
        case Label.ComponentGraphDescription: return "比較に対する先行/遅れを全区間で可視化します。";
        case Label.ComponentSplitsDescription: return "スプリット時間の主要コンポーネント。表形式で表示し、スクロールできます。";
        case Label.ComponentDetailedTimer: return "詳細タイマー";
        case Label.ComponentDetailedTimerDescription: return "総時間と現在セグメント時間などを表示します。";
        case Label.ComponentTimer: return "タイマー";
        case Label.ComponentTimerDescription: return "総時間をデジタル表示し、色は比較に基づきます。";
        case Label.ComponentCurrentComparison: return "現在の比較";
        case Label.ComponentCurrentComparisonDescription: return "現在の比較名を表示します。";
        case Label.ComponentCurrentPace: return "現在のペース";
        case Label.ComponentCurrentPaceDescription: return "選択した比較に基づき最終時間を予測します。";
        case Label.ComponentDelta: return "差";
        case Label.ComponentDeltaDescription: return "比較に対する先行/遅れを表示します。";
        case Label.ComponentPbChance: return "PB 可能性";
        case Label.ComponentPbChanceDescription: return "PB 更新の可能性を表示します。";
        case Label.ComponentPossibleTimeSave: return "節約可能時間";
        case Label.ComponentPossibleTimeSaveDescription: return "現在セグメントの節約可能時間を表示します。";
        case Label.ComponentPreviousSegment: return "前セグメント";
        case Label.ComponentPreviousSegmentDescription: return "前セグメントの増減や潜在節約を表示します。";
        case Label.ComponentSegmentTime: return "セグメント時間";
        case Label.ComponentSegmentTimeDescription: return "選択した比較のセグメント時間を表示します。";
        case Label.ComponentSumOfBest: return "ベスト合計";
        case Label.ComponentSumOfBestDescription: return "履歴に基づく最速完走時間を表示します。";
        case Label.ComponentText: return "テキスト";
        case Label.ComponentTextDescription: return "中央/左右のテキストやカスタム変数を表示します。";
        case Label.ComponentTotalPlaytime: return "総プレイ時間";
        case Label.ComponentTotalPlaytimeDescription: return "カテゴリの総プレイ時間を表示します。";
        case Label.ComponentVariableDescription: return "カスタム変数「{name}」の値を表示するテキストを作成します。";
        case Label.ComponentBlankSpace: return "空白";
        case Label.ComponentBlankSpaceDescription: return "背景のみの空コンポーネントです。";
        case Label.ComponentSeparator: return "区切り";
        case Label.ComponentSeparatorDescription: return "コンポーネント間の区切り線を表示します。";
        case Label.AccuracySeconds: return "秒";
        case Label.AccuracyTenths: return "1/10秒";
        case Label.AccuracyHundredths: return "1/100秒";
        case Label.AccuracyMilliseconds: return "ミリ秒";
        case Label.FontStyle: return "スタイル";
        case Label.FontWeight: return "太さ";
        case Label.FontStretch: return "幅";
        case Label.FontStyleNormal: return "標準";
        case Label.FontStyleItalic: return "斜体";
        case Label.AlignmentAutomatic: return "自動";
        case Label.AlignmentLeft: return "左";
        case Label.AlignmentCenter: return "中央";
        case Label.GradientTransparent: return "透明";
        case Label.GradientPlain: return "単色";
        case Label.GradientVertical: return "垂直";
        case Label.GradientHorizontal: return "水平";
        case Label.GradientAlternating: return "交互";
        case Label.GradientPlainDelta: return "単色差";
        case Label.GradientVerticalDelta: return "垂直差";
        case Label.GradientHorizontalDelta: return "水平差";
        case Label.LayoutBackgroundImage: return "画像";
        case Label.LayoutBackgroundBrightness: return "明るさ";
        case Label.LayoutBackgroundOpacity: return "不透明度";
        case Label.LayoutBackgroundBlur: return "ぼかし";
        case Label.LayoutDirectionVertical: return "垂直";
        case Label.LayoutDirectionHorizontal: return "水平";
        case Label.ColumnKindTime: return "時間";
        case Label.ColumnKindVariable: return "変数";
        case Label.ColumnStartWithEmpty: return "空";
        case Label.ColumnStartWithComparisonTime: return "比較時間";
        case Label.ColumnStartWithComparisonSegmentTime: return "比較セグメント時間";
        case Label.ColumnStartWithPossibleTimeSave: return "節約可能時間";
        case Label.ColumnUpdateWithDontUpdate: return "更新しない";
        case Label.ColumnUpdateWithSplitTime: return "スプリットタイム";
        case Label.ColumnUpdateWithDelta: return "先行/遅れ時間";
        case Label.ColumnUpdateWithDeltaWithFallback: return "先行/遅れ時間（空ならスプリットタイム）";
        case Label.ColumnUpdateWithSegmentTime: return "セグメントタイム";
        case Label.ColumnUpdateWithSegmentDelta: return "節約/損失時間";
        case Label.ColumnUpdateWithSegmentDeltaWithFallback: return "節約/損失時間（空ならセグメントタイム）";
        case Label.ColumnUpdateTriggerOnStartingSegment: return "セグメント開始時";
        case Label.ColumnUpdateTriggerContextual: return "状況に応じて";
        case Label.ColumnUpdateTriggerOnEndingSegment: return "セグメント終了時";
        case Label.ComparisonCurrentComparison: return "現在の比較";
        case Label.CustomVariableNoneAvailable: return "利用可能な変数がありません";
        case Label.CustomVariableNoneAvailableTooltip: return "スプリット編集時の「変数」タブでカスタム変数を定義できます。追加のカスタム変数は自動スプリッターが自動的に提供する場合があります。";
        case Label.HotkeyButtonTooltip: return "クリックしてホットキーを記録します。ゲームパッドのボタンも使用できます。グローバルホットキーは現在利用できません。ゲームパッドのボタンはグローバルに動作します。";
        case Label.ServerConnect: return "接続";
        case Label.ServerDisconnect: return "切断";
        case Label.ServerConnecting: return "接続中...";
        case Label.ServerDisconnecting: return "切断中...";
        case Label.ConnectToServerTitle: return "サーバーに接続";
        case Label.ConnectToServerDescription: return "WebSocket URL を指定してください:";
        case Label.Connect: return "接続";
        case Label.UpdateAvailable: return "LiveSplit One の新しいバージョンがあります。ここをクリックして再読み込みしてください。";
        case Label.UnsavedChangesBeforeUnload: return "未保存の変更があります。本当に LiveSplit One を閉じますか？";
        case Label.OpenSidebarAriaLabel: return "サイドバーを開く";
        case Label.FailedToSaveLayout: return "レイアウトの保存に失敗しました。";
        case Label.FailedToSaveHotkeys: return "ホットキー設定の保存に失敗しました。";
        case Label.FailedToSaveGeneralSettings: return "一般設定の保存に失敗しました。";
        case Label.FailedToSaveSplits: return "スプリットの保存に失敗しました。";
        case Label.LayoutCouldNotBeLoaded: return "レイアウトを読み込めませんでした。LiveSplit または LiveSplit One の有効なレイアウトではない可能性があります。";
        case Label.EmptySplitsNotSupported: return "空のスプリットはサポートされていません。";
        case Label.BugEncountered: return "バグが発生しました:";
        case Label.PleaseReportIssueStart: return "この問題は";
        case Label.ReportHere: return "こちら";
        case Label.PleaseReportIssueEnd: return "に報告してください。";
        case Label.BugReportInstructions: return "この問題の修正に役立つよう、再現手順を記載し、問題が発生したときに使用していたスプリットとレイアウトを添付してください。";
        case Label.LoadFailedPrivateBrowsing: return "LiveSplit One を読み込めませんでした。\nプライベートブラウジングを使用している可能性があります。\nブラウザのプライベートブラウジングの制限により、LiveSplit One はスプリット、レイアウト、その他の設定を保存できません。\nこれらの制限は将来解除される可能性があります。\n今すぐ LiveSplit One を使うには、設定でプライベートブラウジングを無効にしてください。";
        case Label.LoadFailedOutdatedBrowser: return "LiveSplit One を読み込めませんでした。\nブラウザが最新でない可能性があります。\nブラウザまたは iOS のバージョンを更新して、もう一度お試しください。\n別の原因として、広告ブロッカーなどのブラウザ拡張機能が重要なスクリプトへのアクセスをブロックしている可能性があります。";
    }
}
