import { Label } from ".";

export function resolvePolish(text: Label): string {
    switch (text) {
        case Label.Ok: return "OK";
        case Label.Cancel: return "Anuluj";
        case Label.Settings: return "Ustawienia";
        case Label.Language: return "Język";
        case Label.LanguageDescription: return "Ustawia język używany w aplikacji.";
        case Label.LanguageAuto: return "Automatyczny";
        case Label.HotkeysHeading: return "Skróty klawiszowe";
        case Label.GeneralHeading: return "Ogólne";
        case Label.NetworkHeading: return "Sieć";
        case Label.FrameRate: return "Liczba klatek";
        case Label.FrameRateDescription: return "Określa liczbę klatek, z jaką wyświetlany jest timer. „Uwzględnia baterię” próbuje określić typ urządzenia i stan ładowania, aby dobrać odpowiednią liczbę klatek. „Dopasuj do ekranu” sprawia, że timer dopasowuje się do częstotliwości odświeżania ekranu.";
        case Label.FrameRateBatteryAware: return "Uwzględnia baterię";
        case Label.FrameRateMatchScreen: return "Dopasuj do ekranu";
        case Label.SaveOnReset: return "Zapisuj przy resecie";
        case Label.SaveOnResetDescription: return "Określa, czy automatycznie zapisywać splity podczas resetowania timera.";
        case Label.ShowControlButtons: return "Pokaż przyciski sterowania";
        case Label.ShowControlButtonsDescription: return "Określa, czy pokazywać przyciski pod timerem pozwalające nim sterować. Gdy wyłączone, musisz używać skrótów klawiszowych.";
        case Label.ShowManualGameTimeInput: return "Pokaż ręczne wprowadzanie czasu gry";
        case Label.ShowManualGameTimeInputDescription: return "Pokazuje pole tekstowe pod timerem, które pozwala ręcznie wprowadzać czas gry. Uruchamiasz timer i robisz splity, naciskając Enter w polu tekstowym. Upewnij się, że porównujesz z „Czasem gry”.";
        case Label.ManualGameTimeMode: return "Tryb ręcznego czasu gry";
        case Label.ManualGameTimeModeDescription: return "Określa, czy ręcznie wprowadzany czas gry ma być czasem segmentów czy czasem splitów.";
        case Label.ManualGameTimeModeSegmentTimes: return "Czasy segmentów";
        case Label.ManualGameTimeModeSplitTimes: return "Czasy splitów";
        case Label.AlwaysOnTop: return "Zawsze na wierzchu";
        case Label.AlwaysOnTopDescription: return "Utrzymuje okno zawsze na wierzchu innych okien.";
        case Label.SpeedrunComIntegration: return "Integracja ze speedrun.com";
        case Label.SpeedrunComIntegrationDescription: return "Pobiera listę gier, kategorii i rankingi ze speedrun.com.";
        case Label.ServerConnection: return "Połączenie z serwerem";
        case Label.ServerConnectionDescription: return "Pozwala połączyć się z serwerem WebSocket, który może sterować timerem poprzez wysyłanie różnych poleceń. Polecenia są obecnie podzbiorem poleceń obsługiwanych przez oryginalny LiveSplit.";
        case Label.ServerConnectionExperimental: return "Ta funkcja jest eksperymentalna i protokół prawdopodobnie zmieni się w przyszłości.";
        case Label.HotkeyAlreadyInUse: return "Ten skrót klawiszowy jest już używany.";
        case Label.Start: return "Start";
        case Label.Resume: return "Wznów";
        case Label.Pause: return "Pauza";
        case Label.UndoSplit: return "Cofnij split";
        case Label.Reset: return "Reset";
        case Label.SkipSplit: return "Pomiń split";
        case Label.ManualGameTimePlaceholder: return "Ręczny czas gry";
        case Label.LiveSplitLogoAlt: return "Logo LiveSplit";
        case Label.LiveSplitOne: return "LiveSplit One";
        case Label.Splits: return "Splity";
        case Label.Layout: return "Układ";
        case Label.CompareAgainst: return "Porównaj z";
        case Label.RealTime: return "Czas rzeczywisty";
        case Label.GameTime: return "Czas gry";
        case Label.PopOut: return "Otwórz w oknie";
        case Label.About: return "O programie";
        case Label.Back: return "Wstecz";
        case Label.AboutVersionPrefix: return "Wersja:";
        case Label.AboutDescription: return "LiveSplit One to wieloplatformowa wersja LiveSplit — zgrabnego i bardzo konfigurowalnego timera dla speedrunnerów.";
        case Label.AboutViewSource: return "Zobacz kod źródłowy na GitHubie";
        case Label.AboutRecentChanges: return "Ostatnie zmiany";
        case Label.AboutContributors: return "Współtwórcy";
        case Label.Loading: return "Wczytywanie...";
        case Label.Add: return "Dodaj";
        case Label.Import: return "Importuj";
        case Label.OpenSplits: return "Otwórz splity";
        case Label.EditSplits: return "Edytuj splity";
        case Label.ExportSplits: return "Eksportuj splity";
        case Label.CopySplits: return "Kopiuj splity";
        case Label.RemoveSplits: return "Usuń splity";
        case Label.Untitled: return "Bez tytułu";
        case Label.NoCategory: return "—";
        case Label.DiscardChangesTitle: return "Odrzucić zmiany?";
        case Label.DiscardChangesDescription: return "Twoje bieżące splity zostały zmodyfikowane i zawierają niezapisane zmiany. Czy chcesz kontynuować i je odrzucić?";
        case Label.DeleteSplitsTitle: return "Usunąć splity?";
        case Label.DeleteSplitsDescription: return "Czy na pewno chcesz usunąć splity? Tej operacji nie można cofnąć.";
        case Label.SaveBestTimesTitle: return "Zapisać najlepsze czasy?";
        case Label.SaveBestTimesDescription: return "Pobiłeś/aś niektóre z najlepszych czasów. Czy chcesz je zaktualizować?";
        case Label.Yes: return "Tak";
        case Label.No: return "Nie";
        case Label.DontReset: return "Nie resetuj";
        case Label.FailedToExportSplits: return "Nie udało się wyeksportować splitów.";
        case Label.CantImportEmptySplits: return "Nie można importować pustych splitów.";
        case Label.FailedToReadFile: return "Nie udało się odczytać pliku:";
        case Label.FailedToImportSplits: return "Nie udało się zaimportować splitów:";
        case Label.CouldNotParseSplits: return "Nie udało się przetworzyć splitów.";
        case Label.LoadedSplitsInvalid: return "Załadowane splity są nieprawidłowe.";
        case Label.NewSegmentName: return "Czas";
        case Label.EditWhileRunningError: return "Nie możesz edytować splitów, gdy timer działa.";
        case Label.Edit: return "Edytuj";
        case Label.Save: return "Zapisz";
        case Label.Export: return "Eksportuj";
        case Label.FailedToParseTimeSpan: return "Nie udało się przetworzyć TimeSpan";
        case Label.Default: return "Domyślne";
        case Label.Game: return "Gra";
        case Label.Category: return "Kategoria";
        case Label.StartTimerAt: return "Uruchom timer od";
        case Label.Attempts: return "Próby";
        case Label.SplitsEditor: return "Edytor splitów";
        case Label.Variables: return "Zmienne";
        case Label.Rules: return "Zasady";
        case Label.Leaderboard: return "Ranking";
        case Label.InsertAbove: return "Wstaw powyżej";
        case Label.InsertBelow: return "Wstaw poniżej";
        case Label.RemoveSegment: return "Usuń segment";
        case Label.MoveUp: return "Przenieś w górę";
        case Label.MoveDown: return "Przenieś w dół";
        case Label.AddVariable: return "Dodaj zmienną";
        case Label.OpenPbPage: return "Otwórz stronę PB";
        case Label.AssociateRun: return "Powiąż bieg";
        case Label.Icon: return "Ikona";
        case Label.SegmentName: return "Nazwa segmentu";
        case Label.SplitTime: return "Czas splitu";
        case Label.SegmentTime: return "Czas segmentu";
        case Label.BestSegment: return "Najlepszy segment";
        case Label.SpeedrunComVariableTooltip: return "Zmienna speedrun.com specyficzna dla gry.";
        case Label.Region: return "Region";
        case Label.RegionDescription: return "Region gry, która jest rozgrywana.";
        case Label.Platform: return "Platforma";
        case Label.PlatformDescription: return "Platforma, na której grana jest gra.";
        case Label.UsesEmulator: return "Używa emulatora";
        case Label.UsesEmulatorDescription: return "Czy do grania używany jest emulator.";
        case Label.CustomVariableTooltip: return "Niestandardowa zmienna określona przez ciebie. Można ją wyświetlać za pomocą komponentu tekstowego.";
        case Label.NoVariables: return "Obecnie brak niestandardowych zmiennych dla tej gry.";
        case Label.NoVariablesWithSpeedrunCom: return "Obecnie brak zmiennych speedrun.com lub niestandardowych zmiennych dla tej gry.";
        case Label.TimedWithoutLoads: return "są mierzone bez czasów ładowania";
        case Label.TimedWithGameTime: return "są mierzone z Czasem gry";
        case Label.RequireVideoProof: return "wymagają wideo jako dowodu";
        case Label.RunsOfThisGamePrefix: return "Biegi tej gry ";
        case Label.RunsOfThisGameSuffix: return ".";
        case Label.And: return "i";
        case Label.SetIcon: return "Ustaw ikonę";
        case Label.SetIconDescription: return "Pozwala wybrać plik obrazu jako ikonę gry. Niektóre formaty mogą nie działać wszędzie.";
        case Label.DownloadBoxArt: return "Pobierz okładkę";
        case Label.DownloadBoxArtDescription: return "Próbuje pobrać okładkę gry ze speedrun.com, aby ustawić ją jako ikonę gry.";
        case Label.DownloadIcon: return "Pobierz ikonę";
        case Label.DownloadIconDescription: return "Próbuje pobrać ikonę gry ze speedrun.com.";
        case Label.RemoveIcon: return "Usuń ikonę";
        case Label.RemoveIconDescription: return "Usuwa ikonę gry.";
        case Label.CleaningMenu: return "Czyszczenie…";
        case Label.ClearOnlyHistory: return "Wyczyść tylko historię";
        case Label.ClearOnlyHistoryDescription: return "Splity przechowują pełną historię wszystkich biegów, w tym każdy czas segmentu. Te informacje są używane przez różne komponenty. Możesz je wyczyścić. Rekord osobisty, najlepsze czasy segmentów i porównania nie zostaną zmienione.";
        case Label.ClearAllTimes: return "Wyczyść wszystkie czasy";
        case Label.ClearAllTimesDescription: return "Usuwa wszystkie czasy ze splitów, w tym całą historię, tak że splity są całkowicie puste, jakby zostały dopiero utworzone.";
        case Label.CleanSumOfBest: return "Wyczyść sumę najlepszych";
        case Label.CleanSumOfBestDescription: return "Pozwala interaktywnie usunąć potencjalne problemy w historii segmentów, które prowadzą do nieprawidłowej sumy najlepszych segmentów. Jeśli pominiesz split, przy następnym splicie łączny czas segmentu może być szybszy niż suma najlepszych czasów poszczególnych segmentów. To wskaże wszystkie takie przypadki i pozwoli je usuwać pojedynczo, jeśli któreś z nich wydaje się błędne.";
        case Label.ComparisonsMenu: return "Porównania…";
        case Label.AddComparison: return "Dodaj porównanie";
        case Label.AddComparisonDescription: return "Dodaje nowe niestandardowe porównanie, w którym możesz przechowywać dowolne czasy.";
        case Label.ImportComparison: return "Importuj porównanie";
        case Label.ImportComparisonDescription: return "Importuje rekord osobisty z podanego pliku splitów jako porównanie.";
        case Label.GenerateGoalComparison: return "Wygeneruj porównanie celu";
        case Label.GenerateGoalComparisonDescription: return "Generuje niestandardowe porównanie celu na podstawie docelowego czasu, który możesz podać. Czasy porównania są automatycznie zbalansowane na podstawie historii segmentów, tak aby w przybliżeniu odpowiadały czasom splitów dla docelowego czasu. Ponieważ są wypełniane na podstawie historii segmentów, docelowe czasy są ograniczone do zakresu między sumą najlepszych segmentów a sumą najgorszych segmentów. Porównanie jest wypełniane tylko dla wybranej metody pomiaru czasu. Czasy porównania dla drugiej metody nie są przez to modyfikowane, więc możesz wygenerować je ponownie, wybierając drugą metodę, aby wygenerować czasy porównania dla obu metod.";
        case Label.CopyComparison: return "Kopiuj porównanie";
        case Label.CopyComparisonDescription: return "Kopiuje dowolne istniejące porównanie, w tym rekord osobisty lub nawet inne automatycznie dostarczone porównanie, jako nowe niestandardowe porównanie. Możesz na przykład użyć tego, aby zachować Ostatni bieg jako porównanie tak długo, jak chcesz.";
        case Label.SetSegmentIcon: return "Ustaw ikonę";
        case Label.SetSegmentIconDescription: return "Pozwala wybrać plik obrazu jako ikonę segmentu. Niektóre formaty mogą nie działać wszędzie.";
        case Label.RemoveSegmentIcon: return "Usuń ikonę";
        case Label.RemoveSegmentIconDescription: return "Usuwa ikonę segmentu.";
        case Label.Rename: return "Zmień nazwę";
        case Label.RenameDescription: return "Wybierz nową nazwę dla niestandardowego porównania. Istnieją nazwy zastrzeżone, których nie można użyć. Nie można też mieć duplikatów.";
        case Label.CopyAction: return "Kopiuj";
        case Label.CopyDescription: return "Tworzy kopię niestandardowego porównania.";
        case Label.ACopy: return "Kopia";
        case Label.Remove: return "Usuń";
        case Label.RemoveDescription: return "Usuwa niestandardowe porównanie.";
        case Label.AnyPercent: return "Any%";
        case Label.LowPercent: return "Low%";
        case Label.HundredPercent: return "100%";
        case Label.AddComparisonPrompt: return "Podaj nazwę porównania, które chcesz dodać:";
        case Label.ComparisonAddError: return "Nie udało się dodać porównania. Może to być duplikat lub nazwa zastrzeżona.";
        case Label.ImportComparisonPrompt: return "Podaj nazwę porównania, które chcesz zaimportować:";
        case Label.GenerateGoalComparisonPrompt: return "Podaj czas, który chcesz osiągnąć:";
        case Label.Generate: return "Generuj";
        case Label.GenerateGoalComparisonError: return "Nie udało się wygenerować porównania celu. Upewnij się, że podano prawidłowy czas.";
        case Label.CopyComparisonPrompt: return "Podaj nazwę porównania, które chcesz skopiować:";
        case Label.CopyComparisonError: return "Nie udało się skopiować porównania. Porównanie może nie istnieć.";
        case Label.NothingToCleanUp: return "Nie ma nic do wyczyszczenia.";
        case Label.CleanPrompt: return "Wyczyścić?";
        case Label.AssociateRunPrompt: return "Podaj identyfikator speedrun.com lub URL biegu:";
        case Label.Associate: return "Powiąż";
        case Label.InvalidSpeedrunUrl: return "Nieprawidłowy identyfikator lub URL speedrun.com.";
        case Label.AssociateRunError: return "Nie udało się powiązać biegu. Identyfikator może być nieprawidłowy.";
        case Label.AddVariablePrompt: return "Podaj nazwę niestandardowej zmiennej, którą chcesz dodać:";
        case Label.RenameComparison: return "Zmień nazwę porównania";
        case Label.RenameComparisonPrompt: return "Podaj nową nazwę porównania:";
        case Label.ComparisonRenameError: return "Nie udało się zmienić nazwy porównania. Może to być duplikat lub nazwa zastrzeżona.";
        case Label.GameNotFound: return "Nie udało się znaleźć gry.";
        case Label.NoBoxArt: return "Gra nie ma okładki.";
        case Label.DownloadBoxArtError: return "Nie udało się pobrać okładki.";
        case Label.NoGameIcon: return "Gra nie ma ikony.";
        case Label.DownloadIconError: return "Nie udało się pobrać ikony.";
        case Label.Rank: return "Miejsce";
        case Label.Player: return "Gracz";
        case Label.Time: return "Czas";
        case Label.Date: return "Data:";
        case Label.Emulator: return "Emulator";
        case Label.EmulatorTag: return "Emulator";
        case Label.ObsoleteRuns: return "Nieaktualne biegi";
        case Label.Shown: return "Wyświetlane";
        case Label.Hidden: return "Ukryte";
        case Label.OpenLeaderboard: return "Otwórz ranking";
        case Label.Filters: return "Filtry";
        case Label.LayoutEditor: return "Edytor układu";
        case Label.Component: return "Komponent";
        case Label.AddComponent: return "Dodaj komponent";
        case Label.RemoveComponent: return "Usuń komponent";
        case Label.DuplicateComponent: return "Duplikuj komponent";
        case Label.MoveComponentUp: return "Przenieś komponent w górę";
        case Label.MoveComponentDown: return "Przenieś komponent w dół";
        case Label.ComponentTitle: return "Tytuł";
        case Label.ComponentTitleDescription: return "Pokazuje nazwę gry i kategorię, która jest rozgrywana. Dodatkowo można pokazać ikonę gry, liczbę prób oraz łączną liczbę pomyślnie ukończonych biegów.";
        case Label.ComponentGraph: return "Wykres";
        case Label.ComponentGraphDescription: return "Wizualizuje, jak bardzo bieżący bieg był przed lub za wybranym porównaniem podczas całego biegu. Wszystkie pojedyncze delty są pokazane jako punkty na wykresie.";
        case Label.ComponentSplitsDescription: return "Główny komponent do wizualizacji wszystkich czasów splitów. Każdy segment jest pokazany w tabeli z ikoną segmentu, nazwą segmentu, deltą względem wybranego porównania i czasem splitu. Lista zapewnia przewijanie, więc nie każdy segment musi być zawsze widoczny.";
        case Label.ComponentDetailedTimer: return "Szczegółowy timer";
        case Label.ComponentDetailedTimerDescription: return "Pokazuje dwa timery: jeden dla łącznego czasu bieżącego biegu oraz drugi pokazujący czas bieżącego segmentu. Można też wyświetlać inne informacje, takie jak czasy segmentów dla maksymalnie dwóch porównań, ikonę segmentu i nazwę segmentu.";
        case Label.ComponentTimer: return "Timer";
        case Label.ComponentTimerDescription: return "Pokazuje łączny czas bieżącego biegu jako zegar cyfrowy. Kolor wyświetlanego czasu zależy od tego, jak dobrze idzie bieżący bieg względem wybranego porównania.";
        case Label.ComponentCurrentComparison: return "Bieżące porównanie";
        case Label.ComponentCurrentComparisonDescription: return "Pokazuje nazwę porównania, z którym timer aktualnie porównuje.";
        case Label.ComponentCurrentPace: return "Bieżące tempo";
        case Label.ComponentCurrentPaceDescription: return "Pokazuje przewidywany końcowy czas bieżącego biegu. Pozostała część biegu jest przewidywana na podstawie wybranego porównania. Na przykład można wybrać porównanie „Najlepsze segmenty”, aby pokazać najlepszy możliwy czas końcowy bieżącego biegu na podstawie sumy najlepszych segmentów.";
        case Label.ComponentDelta: return "Delta";
        case Label.ComponentDeltaDescription: return "Pokazuje, o ile bieżący bieg jest przed lub za wybranym porównaniem.";
        case Label.ComponentPbChance: return "Szansa PB";
        case Label.ComponentPbChanceDescription: return "Pokazuje, jak prawdopodobne jest, że aktywny bieg pobije rekord osobisty. Jeśli nie ma aktywnego biegu, pokazuje ogólną szansę pobicia rekordu osobistego. W trakcie biegu dynamicznie się zmienia w zależności od tego, jak dobrze idzie bieg.";
        case Label.ComponentPossibleTimeSave: return "Możliwa oszczędność czasu";
        case Label.ComponentPossibleTimeSaveDescription: return "Pokazuje, ile czasu można zaoszczędzić na bieżącym segmencie w porównaniu z wybranym porównaniem, na podstawie najlepszego czasu segmentu. Ten komponent umożliwia także pokazanie „Łącznej możliwej oszczędności czasu” dla pozostałej części bieżącego biegu.";
        case Label.ComponentPreviousSegment: return "Poprzedni segment";
        case Label.ComponentPreviousSegmentDescription: return "Pokazuje, ile czasu zostało zaoszczędzonego lub straconego podczas poprzedniego segmentu na podstawie wybranego porównania. Dodatkowo można wyświetlić możliwą oszczędność czasu dla poprzedniego segmentu. Ten komponent przełącza się na widok „Bieżący segment”, który pokazuje aktywną stratę czasu, gdy tracisz czas na bieżącym segmencie.";
        case Label.ComponentSegmentTime: return "Czas segmentu";
        case Label.ComponentSegmentTimeDescription: return "Pokazuje czas bieżącego segmentu dla wybranego porównania. Jeśli nie określono porównania, używa bieżącego porównania timera.";
        case Label.ComponentSumOfBest: return "Suma najlepszych";
        case Label.ComponentSumOfBestDescription: return "Pokazuje najszybszy możliwy czas ukończenia biegu w bieżącej kategorii, na podstawie informacji zebranych ze wszystkich poprzednich biegów. Często odpowiada to sumie najlepszych czasów segmentów, ale nie zawsze, ponieważ pominięte segmenty mogą wprowadzać połączone segmenty szybsze niż rzeczywista suma najlepszych czasów segmentów. Nazwa jest więc nieco myląca, ale pozostała z powodów historycznych.";
        case Label.ComponentText: return "Tekst";
        case Label.ComponentTextDescription: return "Pokazuje tekst, który określisz. Może to być pojedynczy tekst wyśrodkowany lub podzielony na lewy i prawy tekst, co pasuje do sytuacji, w której masz etykietę i wartość. Istnieje także opcja wyświetlenia niestandardowej zmiennej, którą określisz w edytorze splitów.";
        case Label.ComponentTotalPlaytime: return "Łączny czas gry";
        case Label.ComponentTotalPlaytimeDescription: return "Pokazuje łączną ilość czasu, przez jaki grano w bieżącą kategorię.";
        case Label.ComponentVariableDescription: return "Tworzy komponent tekstowy, który pokazuje wartość niestandardowej zmiennej „{name}”.";
        case Label.ComponentBlankSpace: return "Pusta przestrzeń";
        case Label.ComponentBlankSpaceDescription: return "Pusty komponent, który nie pokazuje nic poza tłem. Służy głównie jako odstęp między innymi komponentami.";
        case Label.ComponentSeparator: return "Separator";
        case Label.ComponentSeparatorDescription: return "Prosty komponent, który renderuje separator między komponentami.";
        case Label.AccuracySeconds: return "Sekundy";
        case Label.AccuracyTenths: return "Dziesiąte";
        case Label.AccuracyHundredths: return "Setne";
        case Label.AccuracyMilliseconds: return "Milisekundy";
        case Label.FontStyle: return "Styl";
        case Label.FontWeight: return "Grubość";
        case Label.FontStretch: return "Rozciągnięcie";
        case Label.FontStyleNormal: return "Normalny";
        case Label.FontStyleItalic: return "Kursywa";
        case Label.AlignmentAutomatic: return "Automatyczne";
        case Label.AlignmentLeft: return "Lewo";
        case Label.AlignmentCenter: return "Środek";
        case Label.GradientTransparent: return "Przezroczysty";
        case Label.GradientPlain: return "Jednolity";
        case Label.GradientVertical: return "Pionowy";
        case Label.GradientHorizontal: return "Poziomy";
        case Label.GradientAlternating: return "Naprzemienny";
        case Label.GradientPlainDelta: return "Jednolita delta";
        case Label.GradientVerticalDelta: return "Pionowa delta";
        case Label.GradientHorizontalDelta: return "Pozioma delta";
        case Label.LayoutBackgroundImage: return "Obraz";
        case Label.LayoutBackgroundBrightness: return "Jasność";
        case Label.LayoutBackgroundOpacity: return "Krycie";
        case Label.LayoutBackgroundBlur: return "Rozmycie";
        case Label.LayoutDirectionVertical: return "Pionowy";
        case Label.LayoutDirectionHorizontal: return "Poziomy";
        case Label.ColumnKindTime: return "Czas";
        case Label.ColumnKindVariable: return "Zmienna";
        case Label.ColumnStartWithEmpty: return "Puste";
        case Label.ColumnStartWithComparisonTime: return "Czas porównania";
        case Label.ColumnStartWithComparisonSegmentTime: return "Czas segmentu porównania";
        case Label.ColumnStartWithPossibleTimeSave: return "Możliwa oszczędność czasu";
        case Label.ColumnUpdateWithDontUpdate: return "Nie aktualizuj";
        case Label.ColumnUpdateWithSplitTime: return "Czas splitu";
        case Label.ColumnUpdateWithDelta: return "Czas przed / za";
        case Label.ColumnUpdateWithDeltaWithFallback: return "Czas przed / za lub czas splitu, jeśli pusty";
        case Label.ColumnUpdateWithSegmentTime: return "Czas segmentu";
        case Label.ColumnUpdateWithSegmentDelta: return "Czas zyskany / stracony";
        case Label.ColumnUpdateWithSegmentDeltaWithFallback: return "Czas zyskany / stracony lub czas segmentu, jeśli pusty";
        case Label.ColumnUpdateTriggerOnStartingSegment: return "Przy rozpoczęciu segmentu";
        case Label.ColumnUpdateTriggerContextual: return "Kontekstowo";
        case Label.ColumnUpdateTriggerOnEndingSegment: return "Przy zakończeniu segmentu";
        case Label.ComparisonCurrentComparison: return "Bieżące porównanie";
        case Label.CustomVariableNoneAvailable: return "Brak dostępnych zmiennych";
        case Label.CustomVariableNoneAvailableTooltip: return "Zmienne niestandardowe można zdefiniować na karcie Zmienne podczas edycji splitów. Dodatkowe zmienne niestandardowe mogą być dostarczane automatycznie przez autosplity.";
        case Label.HotkeyButtonTooltip: return "Kliknij, aby nagrać skrót klawiszowy. Możesz też używać przycisków pada. Globalne skróty klawiszowe są obecnie niemożliwe. Przyciski pada działają globalnie.";
        case Label.ServerConnect: return "Połącz";
        case Label.ServerDisconnect: return "Rozłącz";
        case Label.ServerConnecting: return "Łączenie...";
        case Label.ServerDisconnecting: return "Rozłączanie...";
        case Label.ConnectToServerTitle: return "Połącz z serwerem";
        case Label.ConnectToServerDescription: return "Podaj adres URL WebSocket:";
        case Label.Connect: return "Połącz";
        case Label.UpdateAvailable: return "Dostępna jest nowa wersja LiveSplit One! Kliknij tutaj, aby przeładować.";
        case Label.UnsavedChangesBeforeUnload: return "Masz niezapisane zmiany. Czy na pewno chcesz zamknąć LiveSplit One?";
        case Label.OpenSidebarAriaLabel: return "Otwórz pasek boczny";
        case Label.FailedToSaveLayout: return "Nie udało się zapisać układu.";
        case Label.FailedToSaveHotkeys: return "Nie udało się zapisać ustawień skrótów klawiszowych.";
        case Label.FailedToSaveGeneralSettings: return "Nie udało się zapisać ustawień ogólnych.";
        case Label.FailedToSaveSplits: return "Nie udało się zapisać splitów.";
        case Label.LayoutCouldNotBeLoaded: return "Nie udało się wczytać układu. Może to nie być poprawny układ LiveSplit lub LiveSplit One.";
        case Label.EmptySplitsNotSupported: return "Puste splity nie są obsługiwane.";
        case Label.BugEncountered: return "Napotkano błąd:";
        case Label.PleaseReportIssueStart: return "Zgłoś ten problem ";
        case Label.ReportHere: return "tutaj";
        case Label.PleaseReportIssueEnd: return ".";
        case Label.BugReportInstructions: return "Aby pomóc nam naprawić ten problem, opisz kroki odtwarzania i dołącz splity oraz układ, z których korzystałeś(-aś), gdy wystąpił problem.";
        case Label.LoadFailedPrivateBrowsing: return "Nie udało się uruchomić LiveSplit One.\nByć może używasz trybu prywatnego.\nLiveSplit One nie może zapisywać splitów, układów ani innych ustawień z powodu ograniczeń trybu prywatnego przeglądarki.\nTe ograniczenia mogą zostać zniesione w przyszłości.\nAby teraz uruchomić LiveSplit One, wyłącz tryb prywatny w ustawieniach.";
        case Label.LoadFailedOutdatedBrowser: return "Nie udało się uruchomić LiveSplit One.\nByć może używasz nieaktualnej przeglądarki.\nZaktualizuj przeglądarkę lub iOS i spróbuj ponownie.\nInny powód może stanowić rozszerzenie przeglądarki, np. adblocker, które blokuje dostęp do ważnych skryptów.";
    }
}
