import { Label } from ".";

export function resolveRussian(text: Label): string {
    switch (text) {
        case Label.Ok: return "ОК";
        case Label.Cancel: return "Отмена";
        case Label.Settings: return "Настройки";
        case Label.Language: return "Язык";
        case Label.LanguageDescription: return "Устанавливает язык, используемый в приложении.";
        case Label.LanguageAuto: return "Автоматически";
        case Label.HotkeysHeading: return "Горячие клавиши";
        case Label.GeneralHeading: return "Общие";
        case Label.NetworkHeading: return "Сеть";
        case Label.FrameRate: return "Частота кадров";
        case Label.FrameRateDescription: return "Определяет частоту кадров, с которой отображается таймер. «С учётом батареи» пытается определить тип устройства и состояние зарядки, чтобы выбрать подходящую частоту. «По частоте экрана» заставляет таймер соответствовать частоте обновления экрана.";
        case Label.FrameRateBatteryAware: return "С учётом батареи";
        case Label.FrameRateMatchScreen: return "По частоте экрана";
        case Label.SaveOnReset: return "Сохранять при сбросе";
        case Label.SaveOnResetDescription: return "Определяет, следует ли автоматически сохранять сплиты при сбросе таймера.";
        case Label.ShowControlButtons: return "Показывать кнопки управления";
        case Label.ShowControlButtonsDescription: return "Определяет, следует ли показывать кнопки под таймером для управления им. Если отключено, нужно использовать горячие клавиши.";
        case Label.ShowManualGameTimeInput: return "Показывать ручной ввод игрового времени";
        case Label.ShowManualGameTimeInputDescription: return "Показывает поле ввода под таймером, позволяющее вручную вводить игровое время. Вы запускаете таймер и делаете сплиты, нажимая Enter в поле ввода. Убедитесь, что сравнение идет с «Game Time».";
        case Label.ManualGameTimeMode: return "Режим ручного игрового времени";
        case Label.ManualGameTimeModeDescription: return "Определяет, вводится ли ручное игровое время как времена сегментов или времена сплитов.";
        case Label.ManualGameTimeModeSegmentTimes: return "Времена сегментов";
        case Label.ManualGameTimeModeSplitTimes: return "Времена сплитов";
        case Label.AlwaysOnTop: return "Всегда поверх";
        case Label.AlwaysOnTopDescription: return "Держит окно поверх других окон.";
        case Label.SpeedrunComIntegration: return "Интеграция Speedrun.com";
        case Label.SpeedrunComIntegrationDescription: return "Запрашивает список игр, категорий и таблиц лидеров с speedrun.com.";
        case Label.ServerConnection: return "Подключение к серверу";
        case Label.ServerConnectionDescription: return "Позволяет подключиться к серверу WebSocket, который может управлять таймером, отправляя различные команды. Команды сейчас являются подмножеством команд, поддерживаемых оригинальным LiveSplit.";
        case Label.ServerConnectionExperimental: return "Эта функция экспериментальная, и протокол, вероятно, изменится в будущем.";
        case Label.HotkeyAlreadyInUse: return "Эта горячая клавиша уже используется.";
        case Label.Start: return "Старт";
        case Label.Resume: return "Продолжить";
        case Label.Pause: return "Пауза";
        case Label.UndoSplit: return "Отменить сплит";
        case Label.Reset: return "Сброс";
        case Label.SkipSplit: return "Пропустить сплит";
        case Label.ManualGameTimePlaceholder: return "Ручное игровое время";
        case Label.LiveSplitLogoAlt: return "Логотип LiveSplit";
        case Label.LiveSplitOne: return "LiveSplit One";
        case Label.Splits: return "Сплиты";
        case Label.Layout: return "Макет";
        case Label.CompareAgainst: return "Сравнить с";
        case Label.RealTime: return "Реальное время";
        case Label.GameTime: return "Игровое время";
        case Label.PopOut: return "Окно отдельно";
        case Label.About: return "О программе";
        case Label.Back: return "Назад";
        case Label.AboutVersionPrefix: return "Версия:";
        case Label.AboutDescription: return "LiveSplit One — это мультиплатформенная версия LiveSplit, элегантного и высоко настраиваемого таймера для спидраннеров.";
        case Label.AboutViewSource: return "Посмотреть исходный код на GitHub";
        case Label.AboutRecentChanges: return "Недавние изменения";
        case Label.AboutContributors: return "Участники";
        case Label.Loading: return "Загрузка...";
        case Label.Add: return "Добавить";
        case Label.Import: return "Импорт";
        case Label.OpenSplits: return "Открыть сплиты";
        case Label.EditSplits: return "Редактировать сплиты";
        case Label.ExportSplits: return "Экспортировать сплиты";
        case Label.CopySplits: return "Копировать сплиты";
        case Label.RemoveSplits: return "Удалить сплиты";
        case Label.Untitled: return "Без названия";
        case Label.NoCategory: return "—";
        case Label.DiscardChangesTitle: return "Отбросить изменения?";
        case Label.DiscardChangesDescription: return "Текущие сплиты изменены и содержат несохранённые изменения. Продолжить и отбросить изменения?";
        case Label.DeleteSplitsTitle: return "Удалить сплиты?";
        case Label.DeleteSplitsDescription: return "Вы уверены, что хотите удалить сплиты? Это действие нельзя отменить.";
        case Label.SaveBestTimesTitle: return "Сохранить лучшие времена?";
        case Label.SaveBestTimesDescription: return "Вы побили некоторые из своих лучших времен. Хотите обновить их?";
        case Label.Yes: return "Да";
        case Label.No: return "Нет";
        case Label.DontReset: return "Не сбрасывать";
        case Label.FailedToExportSplits: return "Не удалось экспортировать сплиты.";
        case Label.CantImportEmptySplits: return "Нельзя импортировать пустые сплиты.";
        case Label.FailedToReadFile: return "Не удалось прочитать файл:";
        case Label.FailedToImportSplits: return "Не удалось импортировать сплиты:";
        case Label.CouldNotParseSplits: return "Не удалось разобрать сплиты.";
        case Label.LoadedSplitsInvalid: return "Загруженные сплиты недействительны.";
        case Label.NewSegmentName: return "Время";
        case Label.EditWhileRunningError: return "Нельзя редактировать сплиты, пока таймер запущен.";
        case Label.Edit: return "Редактировать";
        case Label.Save: return "Сохранить";
        case Label.Export: return "Экспорт";
        case Label.FailedToParseTimeSpan: return "Не удалось разобрать TimeSpan";
        case Label.Default: return "По умолчанию";
        case Label.Game: return "Игра";
        case Label.Category: return "Категория";
        case Label.StartTimerAt: return "Старт таймера с";
        case Label.Attempts: return "Попытки";
        case Label.SplitsEditor: return "Редактор сплитов";
        case Label.Variables: return "Переменные";
        case Label.Rules: return "Правила";
        case Label.Leaderboard: return "Таблица лидеров";
        case Label.InsertAbove: return "Вставить выше";
        case Label.InsertBelow: return "Вставить ниже";
        case Label.RemoveSegment: return "Удалить сегмент";
        case Label.MoveUp: return "Вверх";
        case Label.MoveDown: return "Вниз";
        case Label.AddVariable: return "Добавить переменную";
        case Label.OpenPbPage: return "Открыть страницу PB";
        case Label.AssociateRun: return "Связать забег";
        case Label.Icon: return "Иконка";
        case Label.SegmentName: return "Название сегмента";
        case Label.SplitTime: return "Время сплита";
        case Label.SegmentTime: return "Время сегмента";
        case Label.BestSegment: return "Лучший сегмент";
        case Label.SpeedrunComVariableTooltip: return "Переменная speedrun.com, специфичная для игры.";
        case Label.Region: return "Регион";
        case Label.RegionDescription: return "Регион игры, в которую играют.";
        case Label.Platform: return "Платформа";
        case Label.PlatformDescription: return "Платформа, на которой играют.";
        case Label.UsesEmulator: return "Используется эмулятор";
        case Label.UsesEmulatorDescription: return "Используется ли эмулятор для игры.";
        case Label.CustomVariableTooltip: return "Пользовательская переменная, заданная вами. Можно отображать в текстовом компоненте.";
        case Label.NoVariables: return "Сейчас нет пользовательских переменных для этой игры.";
        case Label.NoVariablesWithSpeedrunCom: return "Сейчас нет переменных speedrun.com или пользовательских переменных для этой игры.";
        case Label.TimedWithoutLoads: return "измеряются без времени загрузок";
        case Label.TimedWithGameTime: return "измеряются по игровому времени";
        case Label.RequireVideoProof: return "требуют видео‑доказательство";
        case Label.RunsOfThisGamePrefix: return "Забеги этой игры ";
        case Label.RunsOfThisGameSuffix: return ".";
        case Label.And: return "и";
        case Label.SetIcon: return "Установить иконку";
        case Label.SetIconDescription: return "Выберите изображение для иконки игры. Некоторые форматы могут не поддерживаться.";
        case Label.DownloadBoxArt: return "Скачать обложку";
        case Label.DownloadBoxArtDescription: return "Пытается скачать обложку игры с speedrun.com и установить как иконку.";
        case Label.DownloadIcon: return "Скачать иконку";
        case Label.DownloadIconDescription: return "Пытается скачать иконку игры с speedrun.com.";
        case Label.RemoveIcon: return "Удалить иконку";
        case Label.RemoveIconDescription: return "Удаляет иконку игры.";
        case Label.CleaningMenu: return "Очистка…";
        case Label.ClearOnlyHistory: return "Очистить только историю";
        case Label.ClearOnlyHistoryDescription: return "Сплиты хранят всю историю забегов. Эта операция очищает историю, не затрагивая PB, лучшие сегменты и сравнения.";
        case Label.ClearAllTimes: return "Очистить все времена";
        case Label.ClearAllTimesDescription: return "Удаляет все времена и историю, делая сплиты пустыми.";
        case Label.CleanSumOfBest: return "Очистить сумму лучших";
        case Label.CleanSumOfBestDescription: return "Позволяет интерактивно удалять проблемы в истории сегментов, влияющие на точность суммы лучших сегментов.";
        case Label.ComparisonsMenu: return "Сравнения…";
        case Label.AddComparison: return "Добавить сравнение";
        case Label.AddComparisonDescription: return "Добавляет пользовательское сравнение для хранения времен.";
        case Label.ImportComparison: return "Импортировать сравнение";
        case Label.ImportComparisonDescription: return "Импортирует Personal Best из файла сплитов как сравнение.";
        case Label.GenerateGoalComparison: return "Сгенерировать сравнение цели";
        case Label.GenerateGoalComparisonDescription: return "Создает сравнение на основе целевого времени.";
        case Label.CopyComparison: return "Копировать сравнение";
        case Label.CopyComparisonDescription: return "Копирует существующее сравнение в новое пользовательское сравнение.";
        case Label.SetSegmentIcon: return "Установить иконку";
        case Label.SetSegmentIconDescription: return "Выберите изображение для иконки сегмента. Некоторые форматы могут не поддерживаться.";
        case Label.RemoveSegmentIcon: return "Удалить иконку";
        case Label.RemoveSegmentIconDescription: return "Удаляет иконку сегмента.";
        case Label.Rename: return "Переименовать";
        case Label.RenameDescription: return "Выберите новое имя для пользовательского сравнения. Зарезервированные или дублирующиеся имена нельзя использовать.";
        case Label.CopyAction: return "Копировать";
        case Label.CopyDescription: return "Создает копию пользовательского сравнения.";
        case Label.ACopy: return "Копия";
        case Label.Remove: return "Удалить";
        case Label.RemoveDescription: return "Удаляет пользовательское сравнение.";
        case Label.AnyPercent: return "Any%";
        case Label.LowPercent: return "Low%";
        case Label.HundredPercent: return "100%";
        case Label.AddComparisonPrompt: return "Укажите имя сравнения, которое хотите добавить:";
        case Label.ComparisonAddError: return "Не удалось добавить сравнение. Возможно, имя дублируется или зарезервировано.";
        case Label.ImportComparisonPrompt: return "Укажите имя сравнения, которое хотите импортировать:";
        case Label.GenerateGoalComparisonPrompt: return "Укажите время, которого хотите достичь:";
        case Label.Generate: return "Сгенерировать";
        case Label.GenerateGoalComparisonError: return "Не удалось сгенерировать сравнение цели. Убедитесь, что время указано корректно.";
        case Label.CopyComparisonPrompt: return "Укажите имя сравнения, которое хотите скопировать:";
        case Label.CopyComparisonError: return "Не удалось скопировать сравнение. Возможно, его не существует.";
        case Label.NothingToCleanUp: return "Нечего очищать.";
        case Label.CleanPrompt: return "Очистить?";
        case Label.AssociateRunPrompt: return "Укажите ID или URL speedrun.com для забега:";
        case Label.Associate: return "Связать";
        case Label.InvalidSpeedrunUrl: return "Недействительный ID или URL speedrun.com.";
        case Label.AssociateRunError: return "Не удалось связать забег. ID может быть неверным.";
        case Label.AddVariablePrompt: return "Укажите имя пользовательской переменной для добавления:";
        case Label.RenameComparison: return "Переименовать сравнение";
        case Label.RenameComparisonPrompt: return "Укажите новое имя сравнения:";
        case Label.ComparisonRenameError: return "Не удалось переименовать сравнение. Возможно, имя дублируется или зарезервировано.";
        case Label.GameNotFound: return "Игра не найдена.";
        case Label.NoBoxArt: return "У игры нет обложки.";
        case Label.DownloadBoxArtError: return "Не удалось скачать обложку.";
        case Label.NoGameIcon: return "У игры нет иконки.";
        case Label.DownloadIconError: return "Не удалось скачать иконку.";
        case Label.Rank: return "Место";
        case Label.Player: return "Игрок";
        case Label.Time: return "Время";
        case Label.Date: return "Дата:";
        case Label.Emulator: return "Эмулятор";
        case Label.EmulatorTag: return "Эмулятор";
        case Label.ObsoleteRuns: return "Устаревшие забеги";
        case Label.Shown: return "Показаны";
        case Label.Hidden: return "Скрыты";
        case Label.OpenLeaderboard: return "Открыть таблицу";
        case Label.Filters: return "Фильтры";
        case Label.LayoutEditor: return "Редактор макета";
        case Label.Component: return "Компонент";
        case Label.AddComponent: return "Добавить компонент";
        case Label.RemoveComponent: return "Удалить компонент";
        case Label.DuplicateComponent: return "Дублировать компонент";
        case Label.MoveComponentUp: return "Переместить компонент вверх";
        case Label.MoveComponentDown: return "Переместить компонент вниз";
        case Label.ComponentTitle: return "Заголовок";
        case Label.ComponentTitleDescription: return "Показывает название игры и категории, иконки, попытки и количество завершений.";
        case Label.ComponentGraph: return "График";
        case Label.ComponentGraphDescription: return "Показывает опережение/отставание относительно сравнения по всем сплитам.";
        case Label.ComponentSplitsDescription: return "Основной компонент времен сплитов. Таблица с прокруткой.";
        case Label.ComponentDetailedTimer: return "Детальный таймер";
        case Label.ComponentDetailedTimerDescription: return "Показывает общее время и время текущего сегмента.";
        case Label.ComponentTimer: return "Таймер";
        case Label.ComponentTimerDescription: return "Показывает общее время в цифровом виде; цвет зависит от сравнения.";
        case Label.ComponentCurrentComparison: return "Текущее сравнение";
        case Label.ComponentCurrentComparisonDescription: return "Показывает имя текущего сравнения.";
        case Label.ComponentCurrentPace: return "Текущий темп";
        case Label.ComponentCurrentPaceDescription: return "Прогнозирует финальное время на основе выбранного сравнения.";
        case Label.ComponentDelta: return "Разница";
        case Label.ComponentDeltaDescription: return "Показывает опережение/отставание относительно сравнения.";
        case Label.ComponentPbChance: return "Шанс PB";
        case Label.ComponentPbChanceDescription: return "Показывает вероятность получения PB.";
        case Label.ComponentPossibleTimeSave: return "Возможная экономия времени";
        case Label.ComponentPossibleTimeSaveDescription: return "Показывает возможную экономию времени в текущем сегменте.";
        case Label.ComponentPreviousSegment: return "Предыдущий сегмент";
        case Label.ComponentPreviousSegmentDescription: return "Показывает прирост/потерю и потенциальную экономию предыдущего сегмента.";
        case Label.ComponentSegmentTime: return "Время сегмента";
        case Label.ComponentSegmentTimeDescription: return "Показывает время сегмента для выбранного сравнения.";
        case Label.ComponentSumOfBest: return "Сумма лучших";
        case Label.ComponentSumOfBestDescription: return "Показывает самое быстрое возможное время на основе истории.";
        case Label.ComponentText: return "Текст";
        case Label.ComponentTextDescription: return "Показывает центральный/левый/правый текст и пользовательские переменные.";
        case Label.ComponentTotalPlaytime: return "Общее время игры";
        case Label.ComponentTotalPlaytimeDescription: return "Показывает общее время игры в категории.";
        case Label.ComponentVariableDescription: return "Создает текст, показывающий значение пользовательской переменной «{name}».";
        case Label.ComponentBlankSpace: return "Пустое место";
        case Label.ComponentBlankSpaceDescription: return "Пустой компонент только с фоном.";
        case Label.ComponentSeparator: return "Разделитель";
        case Label.ComponentSeparatorDescription: return "Показывает разделительную линию между компонентами.";
        case Label.AccuracySeconds: return "Секунды";
        case Label.AccuracyTenths: return "Десятые";
        case Label.AccuracyHundredths: return "Сотые";
        case Label.AccuracyMilliseconds: return "Миллисекунды";
        case Label.FontStyle: return "Стиль";
        case Label.FontWeight: return "Вес";
        case Label.FontStretch: return "Растяжение";
        case Label.FontStyleNormal: return "Обычный";
        case Label.FontStyleItalic: return "Курсив";
        case Label.AlignmentAutomatic: return "Автоматически";
        case Label.AlignmentLeft: return "Слева";
        case Label.AlignmentCenter: return "По центру";
        case Label.GradientTransparent: return "Прозрачный";
        case Label.GradientPlain: return "Однотонный";
        case Label.GradientVertical: return "Вертикальный";
        case Label.GradientHorizontal: return "Горизонтальный";
        case Label.GradientAlternating: return "Чередующийся";
        case Label.GradientPlainDelta: return "Однотонная дельта";
        case Label.GradientVerticalDelta: return "Вертикальная дельта";
        case Label.GradientHorizontalDelta: return "Горизонтальная дельта";
        case Label.LayoutBackgroundImage: return "Изображение";
        case Label.LayoutBackgroundBrightness: return "Яркость";
        case Label.LayoutBackgroundOpacity: return "Непрозрачность";
        case Label.LayoutBackgroundBlur: return "Размытие";
        case Label.LayoutDirectionVertical: return "Вертикальный";
        case Label.LayoutDirectionHorizontal: return "Горизонтальный";
        case Label.ColumnKindTime: return "Время";
        case Label.ColumnKindVariable: return "Переменная";
        case Label.ColumnStartWithEmpty: return "Пусто";
        case Label.ColumnStartWithComparisonTime: return "Время сравнения";
        case Label.ColumnStartWithComparisonSegmentTime: return "Время сегмента сравнения";
        case Label.ColumnStartWithPossibleTimeSave: return "Возможная экономия времени";
        case Label.ColumnUpdateWithDontUpdate: return "Не обновлять";
        case Label.ColumnUpdateWithSplitTime: return "Время сплита";
        case Label.ColumnUpdateWithDelta: return "Опережение / отставание";
        case Label.ColumnUpdateWithDeltaWithFallback: return "Опережение / отставание или время сплита, если пусто";
        case Label.ColumnUpdateWithSegmentTime: return "Время сегмента";
        case Label.ColumnUpdateWithSegmentDelta: return "Время сэкономлено / потеряно";
        case Label.ColumnUpdateWithSegmentDeltaWithFallback: return "Время сэкономлено / потеряно или время сегмента, если пусто";
        case Label.ColumnUpdateTriggerOnStartingSegment: return "При начале сегмента";
        case Label.ColumnUpdateTriggerContextual: return "Контекстно";
        case Label.ColumnUpdateTriggerOnEndingSegment: return "При завершении сегмента";
        case Label.ComparisonCurrentComparison: return "Текущее сравнение";
        case Label.CustomVariableNoneAvailable: return "Нет доступных переменных";
        case Label.CustomVariableNoneAvailableTooltip: return "Пользовательские переменные можно определить на вкладке «Переменные» при редактировании сплитов. Дополнительные пользовательские переменные могут автоматически предоставляться авто‑сплиттерами.";
        case Label.HotkeyButtonTooltip: return "Нажмите, чтобы записать горячую клавишу. Также можно использовать кнопки геймпада. Глобальные горячие клавиши сейчас невозможны. Кнопки геймпада работают глобально.";
        case Label.ServerConnect: return "Подключиться";
        case Label.ServerDisconnect: return "Отключиться";
        case Label.ServerConnecting: return "Подключение...";
        case Label.ServerDisconnecting: return "Отключение...";
        case Label.ConnectToServerTitle: return "Подключиться к серверу";
        case Label.ConnectToServerDescription: return "Укажите URL WebSocket:";
        case Label.Connect: return "Подключиться";
        case Label.UpdateAvailable: return "Доступна новая версия LiveSplit One! Нажмите здесь, чтобы перезагрузить.";
        case Label.UnsavedChangesBeforeUnload: return "Есть несохранённые изменения. Вы действительно хотите закрыть LiveSplit One?";
        case Label.OpenSidebarAriaLabel: return "Открыть боковую панель";
        case Label.FailedToSaveLayout: return "Не удалось сохранить раскладку.";
        case Label.FailedToSaveHotkeys: return "Не удалось сохранить настройки горячих клавиш.";
        case Label.FailedToSaveGeneralSettings: return "Не удалось сохранить общие настройки.";
        case Label.FailedToSaveSplits: return "Не удалось сохранить сплиты.";
        case Label.LayoutCouldNotBeLoaded: return "Не удалось загрузить раскладку. Возможно, это недействительная раскладка LiveSplit или LiveSplit One.";
        case Label.EmptySplitsNotSupported: return "Пустые сплиты не поддерживаются.";
        case Label.BugEncountered: return "Вы столкнулись с ошибкой:";
        case Label.PleaseReportIssueStart: return "Пожалуйста, сообщите об этой проблеме ";
        case Label.ReportHere: return "здесь";
        case Label.PleaseReportIssueEnd: return ".";
        case Label.BugReportInstructions: return "Чтобы помочь нам исправить эту проблему, укажите шаги для воспроизведения и приложите сплиты и раскладку, которые вы использовали, когда возникла проблема.";
        case Label.LoadFailedPrivateBrowsing: return "Не удалось загрузить LiveSplit One.\nВозможно, вы используете режим приватного просмотра.\nLiveSplit One не может сохранять сплиты, раскладки или другие настройки из‑за ограничений приватного режима браузера.\nЭти ограничения могут быть сняты в будущем.\nЧтобы использовать LiveSplit One сейчас, отключите приватный режим в настройках.";
        case Label.LoadFailedOutdatedBrowser: return "Не удалось загрузить LiveSplit One.\nВозможно, вы используете устаревший браузер.\nОбновите браузер или версию iOS и попробуйте снова.\nДругая причина может быть в расширении браузера, например блокировщике рекламы, которое блокирует доступ к важным скриптам.";
    }
}
