import { Label } from ".";

export function resolveSpanish(text: Label): string {
    switch (text) {
        case Label.Ok: return "Aceptar";
        case Label.Cancel: return "Cancelar";
        case Label.Settings: return "Configuración";
        case Label.Language: return "Idioma";
        case Label.LanguageDescription: return "Establece el idioma utilizado en la aplicación.";
        case Label.LanguageAuto: return "Automático";
        case Label.HotkeysHeading: return "Atajos de teclado";
        case Label.GeneralHeading: return "General";
        case Label.NetworkHeading: return "Red";
        case Label.FrameRate: return "Tasa de fotogramas";
        case Label.FrameRateDescription: return "Determina la tasa de fotogramas a la que se muestra el temporizador. «Consciente de la batería» intenta determinar el tipo de dispositivo y el estado de carga para elegir una buena tasa de fotogramas. «Igualar a la pantalla» hace que el temporizador coincida con la tasa de refresco de la pantalla.";
        case Label.FrameRateBatteryAware: return "Consciente de la batería";
        case Label.FrameRateMatchScreen: return "Igualar a la pantalla";
        case Label.SaveOnReset: return "Guardar al reiniciar";
        case Label.SaveOnResetDescription: return "Determina si los splits se guardan automáticamente al reiniciar el temporizador.";
        case Label.ShowControlButtons: return "Mostrar botones de control";
        case Label.ShowControlButtonsDescription: return "Determina si se muestran botones debajo del temporizador que permiten controlarlo. Cuando está desactivado, debes usar los atajos de teclado.";
        case Label.ShowManualGameTimeInput: return "Mostrar entrada manual del tiempo de juego";
        case Label.ShowManualGameTimeInputDescription: return "Muestra un cuadro de texto debajo del temporizador que te permite introducir manualmente el tiempo de juego. Inicias el temporizador y haces splits presionando la tecla Enter en el cuadro de texto. Asegúrate de comparar con «Game Time».";
        case Label.ManualGameTimeMode: return "Modo de tiempo de juego manual";
        case Label.ManualGameTimeModeDescription: return "Determina si el tiempo de juego manual se introduce como tiempos de segmento o tiempos de split.";
        case Label.ManualGameTimeModeSegmentTimes: return "Tiempos de segmento";
        case Label.ManualGameTimeModeSplitTimes: return "Tiempos de split";
        case Label.AlwaysOnTop: return "Siempre encima";
        case Label.AlwaysOnTopDescription: return "Mantiene la ventana siempre encima de otras ventanas.";
        case Label.SpeedrunComIntegration: return "Integración con Speedrun.com";
        case Label.SpeedrunComIntegrationDescription: return "Consulta la lista de juegos, categorías y tablas de clasificación de speedrun.com.";
        case Label.ServerConnection: return "Conexión al servidor";
        case Label.ServerConnectionDescription: return "Permite conectarte a un servidor WebSocket que puede controlar el temporizador enviando varios comandos. Los comandos actualmente son un subconjunto de los comandos compatibles con el LiveSplit original.";
        case Label.ServerConnectionExperimental: return "Esta función es experimental y es probable que el protocolo cambie en el futuro.";
        case Label.HotkeyAlreadyInUse: return "El atajo de teclado ya está en uso.";
        case Label.Start: return "Iniciar";
        case Label.Resume: return "Reanudar";
        case Label.Pause: return "Pausar";
        case Label.UndoSplit: return "Deshacer split";
        case Label.Reset: return "Reiniciar";
        case Label.SkipSplit: return "Saltar split";
        case Label.ManualGameTimePlaceholder: return "Tiempo de juego manual";
        case Label.LiveSplitLogoAlt: return "Logotipo de LiveSplit";
        case Label.LiveSplitOne: return "LiveSplit One";
        case Label.Splits: return "Splits";
        case Label.Layout: return "Diseño";
        case Label.CompareAgainst: return "Comparar con";
        case Label.RealTime: return "Tiempo real";
        case Label.GameTime: return "Tiempo de juego";
        case Label.PopOut: return "Ventana emergente";
        case Label.About: return "Acerca de";
        case Label.Back: return "Atrás";
        case Label.AboutVersionPrefix: return "Versión:";
        case Label.AboutDescription: return "LiveSplit One es una versión multiplataforma de LiveSplit, el elegante y altamente personalizable temporizador para speedrunners.";
        case Label.AboutViewSource: return "Ver el código fuente en GitHub";
        case Label.AboutRecentChanges: return "Cambios recientes";
        case Label.AboutContributors: return "Colaboradores";
        case Label.Loading: return "Cargando...";
        case Label.Add: return "Agregar";
        case Label.Import: return "Importar";
        case Label.OpenSplits: return "Abrir splits";
        case Label.EditSplits: return "Editar splits";
        case Label.ExportSplits: return "Exportar splits";
        case Label.CopySplits: return "Copiar splits";
        case Label.RemoveSplits: return "Eliminar splits";
        case Label.Untitled: return "Sin título";
        case Label.NoCategory: return "—";
        case Label.DiscardChangesTitle: return "¿Descartar cambios?";
        case Label.DiscardChangesDescription: return "Tus splits actuales están modificados y tienen cambios sin guardar. ¿Quieres continuar y descartar esos cambios?";
        case Label.DeleteSplitsTitle: return "¿Eliminar splits?";
        case Label.DeleteSplitsDescription: return "¿Seguro que quieres eliminar los splits? Esta operación no se puede deshacer.";
        case Label.SaveBestTimesTitle: return "¿Guardar mejores tiempos?";
        case Label.SaveBestTimesDescription: return "Has superado algunos de tus mejores tiempos. ¿Quieres actualizarlos?";
        case Label.Yes: return "Sí";
        case Label.No: return "No";
        case Label.DontReset: return "No reiniciar";
        case Label.FailedToExportSplits: return "No se pudieron exportar los splits.";
        case Label.CantImportEmptySplits: return "No se pueden importar splits vacíos.";
        case Label.FailedToReadFile: return "No se pudo leer el archivo:";
        case Label.FailedToImportSplits: return "No se pudieron importar los splits:";
        case Label.CouldNotParseSplits: return "No se pudieron analizar los splits.";
        case Label.LoadedSplitsInvalid: return "Los splits cargados no son válidos.";
        case Label.NewSegmentName: return "Tiempo";
        case Label.EditWhileRunningError: return "No puedes editar los splits mientras el temporizador está en marcha.";
        case Label.Edit: return "Editar";
        case Label.Save: return "Guardar";
        case Label.Export: return "Exportar";
        case Label.FailedToParseTimeSpan: return "No se pudo analizar TimeSpan";
        case Label.Default: return "Predeterminado";
        case Label.Game: return "Juego";
        case Label.Category: return "Categoría";
        case Label.StartTimerAt: return "Iniciar temporizador en";
        case Label.Attempts: return "Intentos";
        case Label.SplitsEditor: return "Editor de splits";
        case Label.Variables: return "Variables";
        case Label.Rules: return "Reglas";
        case Label.Leaderboard: return "Clasificación";
        case Label.InsertAbove: return "Insertar arriba";
        case Label.InsertBelow: return "Insertar abajo";
        case Label.RemoveSegment: return "Eliminar segmento";
        case Label.MoveUp: return "Subir";
        case Label.MoveDown: return "Bajar";
        case Label.AddVariable: return "Agregar variable";
        case Label.OpenPbPage: return "Abrir página PB";
        case Label.AssociateRun: return "Asociar run";
        case Label.Icon: return "Icono";
        case Label.SegmentName: return "Nombre del segmento";
        case Label.SplitTime: return "Tiempo del split";
        case Label.SegmentTime: return "Tiempo del segmento";
        case Label.BestSegment: return "Mejor segmento";
        case Label.SpeedrunComVariableTooltip: return "Variable de speedrun.com específica del juego.";
        case Label.Region: return "Región";
        case Label.RegionDescription: return "La región del juego que se está jugando.";
        case Label.Platform: return "Plataforma";
        case Label.PlatformDescription: return "La plataforma en la que se juega.";
        case Label.UsesEmulator: return "Usa emulador";
        case Label.UsesEmulatorDescription: return "Si se está usando un emulador para jugar.";
        case Label.CustomVariableTooltip: return "Variable personalizada definida por ti. Puede mostrarse con el componente de texto.";
        case Label.NoVariables: return "Actualmente no hay variables personalizadas para este juego.";
        case Label.NoVariablesWithSpeedrunCom: return "Actualmente no hay variables de speedrun.com ni variables personalizadas para este juego.";
        case Label.TimedWithoutLoads: return "se cronometran sin tiempos de carga";
        case Label.TimedWithGameTime: return "se cronometran con Game Time";
        case Label.RequireVideoProof: return "requieren prueba en vídeo";
        case Label.RunsOfThisGamePrefix: return "Las runs de este juego ";
        case Label.RunsOfThisGameSuffix: return ".";
        case Label.And: return "y";
        case Label.SetIcon: return "Establecer icono";
        case Label.SetIconDescription: return "Elige una imagen como icono del juego. Algunos formatos pueden no funcionar en todas partes.";
        case Label.DownloadBoxArt: return "Descargar carátula";
        case Label.DownloadBoxArtDescription: return "Intenta descargar la carátula de speedrun.com para usarla como icono del juego.";
        case Label.DownloadIcon: return "Descargar icono";
        case Label.DownloadIconDescription: return "Intenta descargar el icono del juego desde speedrun.com.";
        case Label.RemoveIcon: return "Quitar icono";
        case Label.RemoveIconDescription: return "Quita el icono del juego.";
        case Label.CleaningMenu: return "Limpieza…";
        case Label.ClearOnlyHistory: return "Borrar solo historial";
        case Label.ClearOnlyHistoryDescription: return "Los splits guardan todo el historial de runs. Esto borra el historial sin afectar PB, mejores segmentos ni comparaciones.";
        case Label.ClearAllTimes: return "Borrar todos los tiempos";
        case Label.ClearAllTimesDescription: return "Elimina todos los tiempos y el historial, dejando los splits vacíos.";
        case Label.CleanSumOfBest: return "Limpiar suma de mejores";
        case Label.CleanSumOfBestDescription: return "Permite eliminar problemas en el historial de segmentos que hacen que la suma de mejores segmentos sea inexacta.";
        case Label.ComparisonsMenu: return "Comparaciones…";
        case Label.AddComparison: return "Agregar comparación";
        case Label.AddComparisonDescription: return "Agrega una comparación personalizada donde puedes guardar tiempos.";
        case Label.ImportComparison: return "Importar comparación";
        case Label.ImportComparisonDescription: return "Importa el Personal Best de un archivo de splits como comparación.";
        case Label.GenerateGoalComparison: return "Generar comparación de objetivo";
        case Label.GenerateGoalComparisonDescription: return "Genera una comparación de objetivo basada en un tiempo objetivo.";
        case Label.CopyComparison: return "Copiar comparación";
        case Label.CopyComparisonDescription: return "Copia una comparación existente como nueva comparación personalizada.";
        case Label.SetSegmentIcon: return "Establecer icono";
        case Label.SetSegmentIconDescription: return "Elige una imagen como icono del segmento. Algunos formatos pueden no funcionar en todas partes.";
        case Label.RemoveSegmentIcon: return "Quitar icono";
        case Label.RemoveSegmentIconDescription: return "Quita el icono del segmento.";
        case Label.Rename: return "Renombrar";
        case Label.RenameDescription: return "Elige un nuevo nombre para la comparación personalizada. Nombres reservados o duplicados no están permitidos.";
        case Label.CopyAction: return "Copiar";
        case Label.CopyDescription: return "Crea una copia de la comparación personalizada.";
        case Label.ACopy: return "Copia";
        case Label.Remove: return "Eliminar";
        case Label.RemoveDescription: return "Elimina la comparación personalizada.";
        case Label.AnyPercent: return "Any%";
        case Label.LowPercent: return "Low%";
        case Label.HundredPercent: return "100%";
        case Label.AddComparisonPrompt: return "Especifica el nombre de la comparación que quieres agregar:";
        case Label.ComparisonAddError: return "No se pudo agregar la comparación. Puede estar duplicada o ser un nombre reservado.";
        case Label.ImportComparisonPrompt: return "Especifica el nombre de la comparación que quieres importar:";
        case Label.GenerateGoalComparisonPrompt: return "Especifica el tiempo que quieres alcanzar:";
        case Label.Generate: return "Generar";
        case Label.GenerateGoalComparisonError: return "Error al generar la comparación de objetivo. Asegúrate de indicar un tiempo válido.";
        case Label.CopyComparisonPrompt: return "Especifica el nombre de la comparación que quieres copiar:";
        case Label.CopyComparisonError: return "Error al copiar la comparación. La comparación puede no existir.";
        case Label.NothingToCleanUp: return "No hay nada que limpiar.";
        case Label.CleanPrompt: return "¿Limpiar?";
        case Label.AssociateRunPrompt: return "Especifica el ID o URL de speedrun.com de la run:";
        case Label.Associate: return "Asociar";
        case Label.InvalidSpeedrunUrl: return "ID o URL de speedrun.com inválido.";
        case Label.AssociateRunError: return "No se pudo asociar la run. El ID puede no ser válido.";
        case Label.AddVariablePrompt: return "Especifica el nombre de la variable personalizada que quieres agregar:";
        case Label.RenameComparison: return "Renombrar comparación";
        case Label.RenameComparisonPrompt: return "Especifica el nuevo nombre de la comparación:";
        case Label.ComparisonRenameError: return "No se pudo renombrar la comparación. Puede estar duplicada o ser un nombre reservado.";
        case Label.GameNotFound: return "No se encontró el juego.";
        case Label.NoBoxArt: return "El juego no tiene carátula.";
        case Label.DownloadBoxArtError: return "No se pudo descargar la carátula.";
        case Label.NoGameIcon: return "El juego no tiene icono.";
        case Label.DownloadIconError: return "No se pudo descargar el icono.";
        case Label.Rank: return "Puesto";
        case Label.Player: return "Jugador";
        case Label.Time: return "Tiempo";
        case Label.Date: return "Fecha:";
        case Label.Emulator: return "Emulador";
        case Label.EmulatorTag: return "Emulador";
        case Label.ObsoleteRuns: return "Runs obsoletas";
        case Label.Shown: return "Mostradas";
        case Label.Hidden: return "Ocultas";
        case Label.OpenLeaderboard: return "Abrir clasificación";
        case Label.Filters: return "Filtros";
        case Label.LayoutEditor: return "Editor de diseño";
        case Label.Component: return "Componente";
        case Label.AddComponent: return "Agregar componente";
        case Label.RemoveComponent: return "Eliminar componente";
        case Label.DuplicateComponent: return "Duplicar componente";
        case Label.MoveComponentUp: return "Mover componente hacia arriba";
        case Label.MoveComponentDown: return "Mover componente hacia abajo";
        case Label.ComponentTitle: return "Título";
        case Label.ComponentTitleDescription: return "Muestra el nombre del juego y la categoría, iconos, intentos y número de finalizaciones.";
        case Label.ComponentGraph: return "Gráfico";
        case Label.ComponentGraphDescription: return "Muestra el adelanto/retraso respecto a la comparación en todos los splits.";
        case Label.ComponentSplitsDescription: return "El componente principal de los tiempos de split. Muestra una tabla desplazable.";
        case Label.ComponentDetailedTimer: return "Temporizador detallado";
        case Label.ComponentDetailedTimerDescription: return "Muestra el tiempo total y el tiempo del segmento actual.";
        case Label.ComponentTimer: return "Temporizador";
        case Label.ComponentTimerDescription: return "Muestra el tiempo total en formato digital; el color depende de la comparación.";
        case Label.ComponentCurrentComparison: return "Comparación actual";
        case Label.ComponentCurrentComparisonDescription: return "Muestra el nombre de la comparación actual.";
        case Label.ComponentCurrentPace: return "Ritmo actual";
        case Label.ComponentCurrentPaceDescription: return "Predice el tiempo final según la comparación seleccionada.";
        case Label.ComponentDelta: return "Diferencia";
        case Label.ComponentDeltaDescription: return "Muestra el adelanto/retraso respecto a la comparación.";
        case Label.ComponentPbChance: return "Probabilidad de PB";
        case Label.ComponentPbChanceDescription: return "Muestra la probabilidad de conseguir un PB.";
        case Label.ComponentPossibleTimeSave: return "Ahorro de tiempo posible";
        case Label.ComponentPossibleTimeSaveDescription: return "Muestra el tiempo que se puede ahorrar en el segmento actual.";
        case Label.ComponentPreviousSegment: return "Segmento anterior";
        case Label.ComponentPreviousSegmentDescription: return "Muestra la ganancia/pérdida y el ahorro potencial del segmento anterior.";
        case Label.ComponentSegmentTime: return "Tiempo de segmento";
        case Label.ComponentSegmentTimeDescription: return "Muestra el tiempo del segmento para la comparación seleccionada.";
        case Label.ComponentSumOfBest: return "Suma de mejores";
        case Label.ComponentSumOfBestDescription: return "Muestra el tiempo más rápido posible según el historial.";
        case Label.ComponentText: return "Texto";
        case Label.ComponentTextDescription: return "Muestra texto central/izquierda/derecha y variables personalizadas.";
        case Label.ComponentTotalPlaytime: return "Tiempo total de juego";
        case Label.ComponentTotalPlaytimeDescription: return "Muestra el tiempo total jugado en la categoría.";
        case Label.ComponentVariableDescription: return "Crea texto que muestra el valor de la variable personalizada «{name}».";
        case Label.ComponentBlankSpace: return "Espacio en blanco";
        case Label.ComponentBlankSpaceDescription: return "Componente vacío con solo el fondo.";
        case Label.ComponentSeparator: return "Separador";
        case Label.ComponentSeparatorDescription: return "Muestra una línea separadora entre componentes.";
        case Label.AccuracySeconds: return "Segundos";
        case Label.AccuracyTenths: return "Décimas";
        case Label.AccuracyHundredths: return "Centésimas";
        case Label.AccuracyMilliseconds: return "Milisegundos";
        case Label.FontStyle: return "Estilo";
        case Label.FontWeight: return "Peso";
        case Label.FontStretch: return "Estiramiento";
        case Label.FontStyleNormal: return "Normal";
        case Label.FontStyleItalic: return "Cursiva";
        case Label.AlignmentAutomatic: return "Automático";
        case Label.AlignmentLeft: return "Izquierda";
        case Label.AlignmentCenter: return "Centro";
        case Label.GradientTransparent: return "Transparente";
        case Label.GradientPlain: return "Sólido";
        case Label.GradientVertical: return "Vertical";
        case Label.GradientHorizontal: return "Horizontal";
        case Label.GradientAlternating: return "Alternado";
        case Label.GradientPlainDelta: return "Delta sólido";
        case Label.GradientVerticalDelta: return "Delta vertical";
        case Label.GradientHorizontalDelta: return "Delta horizontal";
        case Label.LayoutBackgroundImage: return "Imagen";
        case Label.LayoutBackgroundBrightness: return "Brillo";
        case Label.LayoutBackgroundOpacity: return "Opacidad";
        case Label.LayoutBackgroundBlur: return "Desenfoque";
        case Label.LayoutDirectionVertical: return "Vertical";
        case Label.LayoutDirectionHorizontal: return "Horizontal";
        case Label.ColumnKindTime: return "Tiempo";
        case Label.ColumnKindVariable: return "Variable";
        case Label.ColumnStartWithEmpty: return "Vacío";
        case Label.ColumnStartWithComparisonTime: return "Tiempo de comparación";
        case Label.ColumnStartWithComparisonSegmentTime: return "Tiempo de segmento de comparación";
        case Label.ColumnStartWithPossibleTimeSave: return "Tiempo posible de ahorrar";
        case Label.ColumnUpdateWithDontUpdate: return "No actualizar";
        case Label.ColumnUpdateWithSplitTime: return "Tiempo del split";
        case Label.ColumnUpdateWithDelta: return "Tiempo a favor / en contra";
        case Label.ColumnUpdateWithDeltaWithFallback: return "Tiempo a favor / en contra o tiempo del split si está vacío";
        case Label.ColumnUpdateWithSegmentTime: return "Tiempo de segmento";
        case Label.ColumnUpdateWithSegmentDelta: return "Tiempo ganado / perdido";
        case Label.ColumnUpdateWithSegmentDeltaWithFallback: return "Tiempo ganado / perdido o tiempo de segmento si está vacío";
        case Label.ColumnUpdateTriggerOnStartingSegment: return "Al iniciar el segmento";
        case Label.ColumnUpdateTriggerContextual: return "Contextual";
        case Label.ColumnUpdateTriggerOnEndingSegment: return "Al terminar el segmento";
        case Label.ComparisonCurrentComparison: return "Comparación actual";
        case Label.CustomVariableNoneAvailable: return "No hay variables disponibles";
        case Label.CustomVariableNoneAvailableTooltip: return "Las variables personalizadas se pueden definir en la pestaña Variables al editar splits. Variables personalizadas adicionales pueden ser proporcionadas automáticamente por auto splitters.";
        case Label.HotkeyButtonTooltip: return "Haz clic para grabar un atajo. También puedes usar botones de gamepad. Los atajos globales no son posibles actualmente. Los botones del gamepad funcionan de forma global.";
        case Label.ServerConnect: return "Conectar";
        case Label.ServerDisconnect: return "Desconectar";
        case Label.ServerConnecting: return "Conectando...";
        case Label.ServerDisconnecting: return "Desconectando...";
        case Label.ConnectToServerTitle: return "Conectar al servidor";
        case Label.ConnectToServerDescription: return "Indica la URL de WebSocket:";
        case Label.Connect: return "Conectar";
        case Label.UpdateAvailable: return "¡Hay una nueva versión de LiveSplit One disponible! Haz clic aquí para recargar.";
        case Label.UnsavedChangesBeforeUnload: return "Hay cambios sin guardar. ¿Seguro que quieres cerrar LiveSplit One?";
        case Label.OpenSidebarAriaLabel: return "Abrir barra lateral";
        case Label.FailedToSaveLayout: return "No se pudo guardar el diseño.";
        case Label.FailedToSaveHotkeys: return "No se pudieron guardar los atajos de teclado.";
        case Label.FailedToSaveGeneralSettings: return "No se pudieron guardar los ajustes generales.";
        case Label.FailedToSaveSplits: return "No se pudieron guardar los splits.";
        case Label.LayoutCouldNotBeLoaded: return "No se pudo cargar el diseño. Es posible que no sea un diseño válido de LiveSplit o LiveSplit One.";
        case Label.EmptySplitsNotSupported: return "No se admiten splits vacíos.";
        case Label.BugEncountered: return "Encontraste un error:";
        case Label.PleaseReportIssueStart: return "Por favor, informa de este problema ";
        case Label.ReportHere: return "aquí";
        case Label.PleaseReportIssueEnd: return ".";
        case Label.BugReportInstructions: return "Para ayudarnos a corregir este problema, incluye los pasos para reproducirlo y adjunta los splits y el diseño que estabas usando cuando ocurrió el problema.";
        case Label.LoadFailedPrivateBrowsing: return "No se pudo cargar LiveSplit One.\nEs posible que estés en modo de navegación privada.\nLiveSplit One no puede almacenar splits, diseños u otros ajustes debido a las limitaciones de la navegación privada del navegador.\nEstas limitaciones podrían eliminarse en el futuro.\nPara usar LiveSplit One por ahora, desactiva la navegación privada en tus ajustes.";
        case Label.LoadFailedOutdatedBrowser: return "No se pudo cargar LiveSplit One.\nEs posible que estés usando un navegador desactualizado.\nActualiza tu navegador o tu versión de iOS e inténtalo de nuevo.\nOtra posible causa es una extensión del navegador, como un bloqueador de anuncios, que esté bloqueando el acceso a scripts importantes.";
    }
}
